chanzuckerberg/single-cell-curation

Makefile, cellxgene_schema_cli/setup.py
Add targets for building and releasing cellxgene-schema to pypi.
=> Add target for creating and uploading a distribution

schema/2.0.0/corpora_schema.md
=> 2.0.0 editorial

schema/2.0.0/corpora_schema.md
=> Clarified numpy.ndarray requirement for obsm

schema/2.0.0/corpora_schema.md
Adds requirements to `raw.var` which must be identical to `var`.
=> Add raw.var requirements

schema/2.0.0/corpora_schema.md
=> Update pinned ontology versions

cellxgene_schema_cli/cellxgene_schema/ontology_files/owl_info.yml
Updates ontology info yaml file as well as the reference `all_ontology.json.gz`
closes https://github.com/chanzuckerberg/single-cell-curation/issues/112
=> Update pinned ontologies for validator

schema/2.0.0/schema.md, schema/2.0.0/single_cell_matrix_schema.md
=> Rename corpora_schema.md to single_cell_matrix_schema.md and fix internal references

.github/workflows/python-app.yml
This PR adds a "python application" workflow that will automate running lint and unittests on `cellxgene-schema`
=> Create workflow for unittests of cellxgene-schema

cellxgene_schema_cli/CHANGELOG.md
`CHANGELOG.md` update corresponding to #172
=> chore: updated CHANGELOG.md (#172)

cellxgene_schema_cli/setup.py
=> Undo manual bump of version

docs/release_process.md
* added prerequisites section to release_process.md (#162 )
=> Release process doc updates

.bumpversion.cfg, Makefile, cellxgene_schema_cli/CHANGELOG.md, cellxgene_schema_cli/setup.py, docs/release_process.md
Tested and ready to go.
https://test.pypi.org/project/cellxgene-schema/2.1.1/
=> Release version 2.1.1

cellxgene_schema_cli/cellxgene_schema/write_labels.py
=> fix: add feature name and reference to raw.var

notebooks/curation_api/sample_local_dataset_upload_dev.py.ipynb
chore: update python dev notebook
- Retrieve upload key prefix from credentials endpoint
- Update instructions to incorporate Dataset uuid option
- Other minor adjustments for clarity
=> chore: python notebook improvements

schema/3.0.0/schema.md
=> Deprecate ethnicity_ontology_term_id and ethnicity

schema/3.0.0/schema.md
=> Names must not start with "__"

schema/3.0.0/schema.md
=> Replace final with normalized

schema/3.0.0/schema.md
=> Added further recommendations for donor_id design

schema/3.0.0/schema.md
Closes #227 
The _spatial proteomics_ link is not live yet because EFO released this morning.
=> Suspension type

schema/3.0.0/schema.md
Closes #232 
Closes #181
Closes #235
=> Editorial updates and Anndata 0.8

schema/3.0.0/schema.md
=> Update pinned ontologies

cellxgene_schema_cli/cellxgene_schema/validate.py, cellxgene_schema_cli/tests/test_schema_compliance.py
Note: this solves issue number 3 from the ticket.
=> chore: fix errors for feature_is_filtered

schema/3.0.0/schema.md, schema/3.0.0/seurat_encoding.md
=> Update Seurat encoding

notebooks/curation_api/python/get_collections.ipynb, notebooks/curation_api/python/src/collection.py
=> Update python notebooks with the curator query parameter

notebooks/curation_api/R/create_collection_R.ipynb, notebooks/curation_api/python/create_collection.ipynb, notebooks/curation_api/python/src/dataset.py, notebooks/curation_api/python_raw/create_collection.ipynb
- some minor doc updates
- identifier regex was using the wrong named regex
=> fix: id regex

notebooks/curation_api/R/create_dataset_from_local_file_R.ipynb, notebooks/curation_api/python/src/dataset.py, notebooks/curation_api/python_raw/create_dataset_from_local_file.ipynb
Had neglected to update the credentials endpoint in the notebook when Trent made this refactor last week.
=> fix: update endpoint for s3 credentials

schema/3.0.0/schema.md
=> Refreshed pinned ontologies for 3.0.0

cellxgene_schema_cli/cellxgene_schema/convert.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/346
=> chore: add new ontology conversions to convert command

schema/3.0.0/schema.md, schema/3.0.0/seurat_encoding.md
=> final 3.0.0

LICENSE.txt
https://github.com/chanzuckerberg/single-cell/issues/403
=> chore: Update license copyright year

notebooks/curation_api/R/get_datasets_R.ipynb, notebooks/curation_api/python/get_datasets.ipynb, notebooks/curation_api/python/src/dataset.py, notebooks/curation_api/python_raw/get_datasets.ipynb
Sister PR for [this endpoint](https://github.com/chanzuckerberg/single-cell-data-portal/pull/4331)
=> add datasets index notebooks

notebooks/curation_api/R/get_dataset_version_R.ipynb, notebooks/curation_api/python/get_dataset_version.ipynb, notebooks/curation_api/python/src/dataset.py, notebooks/curation_api/python_raw/get_dataset_version.ipynb
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4326
=> feat: add notebooks for get dataset version endpoint

notebooks/curation_api/R/get_dataset_versions_R.ipynb, notebooks/curation_api/python/example_workflow.ipynb, notebooks/curation_api/python/get_dataset_versions.ipynb, notebooks/curation_api/python/src/dataset.py, notebooks/curation_api/python_raw/get_dataset_versions.ipynb
https://github.com/chanzuckerberg/single-cell-data-portal/issues/4329
=> feat: add notebooks for fetching all published versions for a given dataset

notebooks/curation_api/R/get_collection_version_R.ipynb, notebooks/curation_api/python/example_workflow.ipynb, notebooks/curation_api/python/get_collection_version.ipynb, notebooks/curation_api/python/src/collection.py, notebooks/curation_api/python_raw/get_collection_version.ipynb
https://github.com/chanzuckerberg/single-cell-data-portal/issues/4327
=> feat: create notebooks for fetching a collection version

notebooks/curation_api/python/src/dataset.py, notebooks/curation_api/python/src/utils/config.py, notebooks/curation_api/python/src/utils/http.py
https://github.com/chanzuckerberg/single-cell-data-portal/issues/4627
=> fix: make env vars capitalized to fit pre-commit linting

cellxgene_schema_cli/Makefile, cellxgene_schema_cli/scripts/update_genes.py
The make recipe was broken and the paths were not setup correctly in the script to run.
=> fix update-genes

schema_bump_dry_run_scripts/genes/report_template.jinja, schema_bump_dry_run_scripts/genes/tests/test_gene_bump_dry_run.py
=> fix(gencode report): change term to feature

.github/workflows/minor-schema-version-bump.yml, .github/workflows/ontology_process.yml
Reverts chanzuckerberg/single-cell-curation#486
=> Revert "Tsmith/demo minor schema update"

.bumpversion.cfg, .github/workflows/minor-schema-version-bump.yml, .github/workflows/ontology_process.yml, cellxgene_schema_cli/setup.py
TODO For Testers to Demo Workflow: 
- In single commit:
- Update link to downloadable reference owl file in owl_info.yml for any ontologies you'd like to update
- Update version number for GENCODE reference you'd like to update in gene_info.yml
- Wait for ontology processing workflow to run, and commit to this branch with message "AUTO: update ontologies"
- Merge and kickoff: gene feature dry run, ontology dry run, publish minor schema update of cellxgene-schema-cli to (test) pypi, and creation of Migrate script PR (can follow workflows under 'Actions' tab)
=> chore: set-up interactive demo branch

.github/workflows/minor-schema-version-bump.yml
specify files to commit to avoid committing extra files.
=> fix(migrate): specify files to commit

.github/workflows/minor-schema-version-bump.yml
- the *_diff.txt files will not longer be needed at this point and will cause conflict with future migrations if they are not removed.
=> feat(migration): removed *_diff.txt files after generating migration.py

cellxgene_schema_cli/scripts/ontology_processing.py, scripts/schema_bump_dry_run_ontologies/ontology_bump_dry_run.py, scripts/schema_bump_dry_run_ontologies/tests/fixtures/with_term_tracker_expected, scripts/schema_bump_dry_run_ontologies/tests/test_ontology_bump_dry_run.py
#537
Tested downloading ontologies locally
=> feat: include term tracker URL in ontology curator report

schema/3.1.0/schema.md
=> Updated ontologies and gene references

schema/3.1.0/schema.md
=> Updated assay_ontology_term_id recommendations

schema/3.1.0/schema.md
=> Updated schema_version requirements

schema/3.1.0/schema.md
=> Added section for schema versioning

cellxgene_schema_cli/cellxgene_schema/cli.py, cellxgene_schema_cli/cellxgene_schema/convert.py
Add warnings that convert will be deprecated in 4.0.0
=> warning for deprecated convert

schema/3.1.0/schema.md
=> Updated references to OLS4

schema/4.0.0/schema.md, schema/4.0.0/seurat_encoding.md
=> Added tissue_type

schema/4.0.0/schema.md, schema/4.0.0/seurat_encoding.md
=> Added feature_length

schema/4.0.0/schema.md, schema/4.0.0/seurat_encoding.md
=> Added citation to uns

schema/4.0.0/schema.md
=> Add obs index

schema/4.0.0/seurat_encoding.md
=> Editorial updates

.github/workflows/minor-schema-version-bump.yml, cellxgene_schema_cli/cellxgene_schema/ontology_files/owl_info.yml
Trigger e2e schema minor bump in dev
=> Update Ontologies for Schema 3.1.0

schema/4.0.0/schema.md
=> Add {column}_colors

schema/4.0.0/schema.md
=> Update obsm embeddings

schema/4.0.0/schema.md
=> Added observation_joinid

.github/workflows/minor-schema-version-bump.yml, .github/workflows/trigger-schema-migration.yml, scripts/compute_mappings/compute_ancestor_mapping.ipynb, scripts/compute_mappings/compute_ancestor_mapping.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4832
=> fix: filepath in compute_ancestor_mapping + productionize GHA workflows

scripts/compute_mappings/compute_ancestor_mapping.ipynb, scripts/compute_mappings/compute_ancestor_mapping.py
replace "_" with ":" in ontology terms when mapping to development_stage_ancestors.json, for compatibility with frontend filters
=> fix: update compute_ancestor_mapping script to match data-portal formatting

.github/workflows/push_tests.yml, Makefile, scripts/schema_bump_dry_run_ontologies/tests/test_ontology_bump_dry_run.py
- enable code coverage for tests running in the /scripts path
- light reorganizing of makefile
=> fix: enable codecov for new tests

schema/4.0.0/schema.md
Closes #597 
I also moved the existing `obsm` section to follow `obs`.
=> updated requirements for ndarrays in obsm, obsp, varm, varp

schema/4.0.0/schema.md
=> Clarified requirements for schema_version

schema/4.0.0/schema.md
=> updated requirements for raw matrices

schema/4.0.0/schema.md
=> Updated pinned ontology releases

cellxgene_schema_cli/cellxgene_schema/validate.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/590
not sure what the best way to test this is
=> feat: improve validation to X_{suffix} embeddings

PULL_REQUEST_TEMPLATE.md
- https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/562
- add PR template with proposed QA process for CLI changes
- no tests, doc change
=> feat: add PR template

cellxgene_schema_cli/cellxgene_schema/ontology_files/owl_info.yml
- #616 
- If the reason for this PR's code changes are not clear in the issue, state value/impact
- Update specified pinned ontologies
```
```
=> chore: update pinned ontologies

cellxgene_schema_cli/cellxgene_schema/validate.py, cellxgene_schema_cli/tests/test_schema_compliance.py
- based on some feedback [here](https://github.com/chanzuckerberg/single-cell-curation/issues/590#issuecomment-1749823296), it would be useful to clarify the warning message
- updated some english
updated tests as needed
=> feat: update warning message

scripts/compute_mappings/compute_tissue_and_cell_type_mappings.py
see https://czi-sci.slack.com/archives/C024HCSH9PT/p1697232968315399 and https://czi-sci.slack.com/archives/C024HCSH9PT/p1700261725188729
Expands list of Cell Classes and Sublclasses to reduce number of orphan cell types
see  https://docs.google.com/spreadsheets/d/1ntR-yK2i6k1iTpejosy1ymUxwD-BCYvWgQPXG8DgVf0/edit#gid=0
=> Update hand-curated list of Cell Classes and Subclasses

schema/4.0.0/schema.md
=> Updated X_suffix requirements

schema/4.1.0/schema.md
=> Added stricter requirements for assay_ontology_term_id

schema/4.1.0/schema.md
=> Added stricter requirements for disease_ontology_term_id

schema/4.1.0/schema.md
=> Updated GENCODE references

schema/4.1.0/schema.md
=> Replace native cell with unknown

schema/4.1.0/schema.md
=> Prohibit zero length values in uns

schema/4.1.0/schema.md
=> Updated pinned ontologies

schema/4.1.0/schema.md
=> Update reserved and unique requirements

cellxgene_schema_cli/cellxgene_schema/validate.py, cellxgene_schema_cli/tests/test_schema_compliance.py
- #729 
- Followup: include assessment of `raw.var`
- 
- unit tests
```
```
=> feat: unique raw.var columns

cellxgene_schema_cli/cellxgene_schema/validate.py, cellxgene_schema_cli/tests/test_schema_compliance.py
follow up to https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/728
allows none, true, and false values for `uns` fields
added unit tests
=> feat: allow none / true / false values

.github/workflows/gencode-bump-dry-run.yml, .github/workflows/schema-version-bump.yml
https://czi-sci.slack.com/archives/C06AVGFV222/p1707496101878469?thread_ts=1707494549.816149&cid=C06AVGFV222
bumping the role duration should hopefully resolve the aws failures
n/a
=> feat: bump aws role durations for dry runs

cellxgene_schema_cli/cellxgene_schema/migrate.py, cellxgene_schema_cli/cellxgene_schema/utils.py, cellxgene_schema_cli/tests/test_migrate.py, cellxgene_schema_cli/tests/test_utils.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/726
- adds the remapped gencode terms
added tests to `test_migrate.py` and `test_utils.`py
=> feat: update migrate script to remap gencode terms

scripts/schema_bump_dry_run_genes/gene_bump_dry_run.py
the way we would re-discover this issue in the future is by running the GENCODE dry run script. i think it would be useful to link to the data-portal ticket so that someone in the future doesn't need to spend as much time investigating it as i did :)
- adds a link to https://github.com/chanzuckerberg/single-cell-data-portal/issues/6695 via code comment
n/a
=> chore: add comment linking to github issue

cellxgene_schema_cli/requirements.txt, scripts/compute_mappings/requirements.txt
…ments
- #TICKET_NUMBER
- If the reason for this PR's code changes are not clear in the issue, state value/impact
- 
```
```
=> chore: update owlready for compatibility with data portal processing reqs

cellxgene_schema_cli/cellxgene_schema/migrate.py
- https://github.com/chanzuckerberg/single-cell/issues/684
- 
```
```
=> chore: delete uns keys with empty values per Schema 5.0 validation reqs

cellxgene_schema_cli/cellxgene_schema/migrate.py, cellxgene_schema_cli/cellxgene_schema/validate.py, cellxgene_schema_cli/tests/test_schema_compliance.py
- #728 
- If the reason for this PR's code changes are not clear in the issue, state value/impact
- 
```
```
=> fix: handle scipy matrices in uns empty value check

cellxgene_schema_cli/cellxgene_schema/migrate.py
https://czi-sci.slack.com/archives/C06AVGFV222/p1710191792062559?thread_ts=1710175897.417769&cid=C06AVGFV222
- 
```
```
=> chore: remove parentheses and leading underscores in migrate script

cellxgene_schema_cli/cellxgene_schema/validate.py, cellxgene_schema_cli/tests/test_schema_compliance.py
- #819 
- Add logic to permit numeric values
- unit tested
```
```
=> feat: allow numbers as uns values

cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- [single-cell-data-portal #6629](https://github.com/chanzuckerberg/single-cell-data-portal/issues/6629)
- Update schema version header in schema definition yml
```
```
=> docs: update schema version in schema definition yml

.github/workflows/gencode-process.yml, .github/workflows/generate-conversion-script.yml, .github/workflows/schema-version-bump.yml, cellxgene_schema_cli/MANIFEST.in, cellxgene_schema_cli/scripts/gene_processing.py
- missed some spots when doing directory rename + removing compute scripts
=> fix: rename ontology_files and ONTOLOGY_DIR references to gencode_files and GENCODE_DIR

notebooks/curation_api/python/get_datasets.ipynb, notebooks/curation_api/python/src/dataset.py
- #4841
- Updated datasets demo to include `visibility` and `schema_version`.
=> feat: datasets demo with visibility

schema/5.1.0/schema.md
=> restored 3.1.0 obsm requirements

schema/5.1.0/schema.md
=> updated image requirements

schema/5.1.0/schema.md
=> Updated requirements for assay_ontology_term_id

cellxgene_schema_cli/cellxgene_schema/validate.py, cellxgene_schema_cli/tests/fixtures/examples_validate.py, cellxgene_schema_cli/tests/test_validate.py
- #830 
- Added validation of cell ontology term ID: must be "unknown" if Visium, `is_single` is True and `in_tissue` is 0.
- Added unit tests.
=> feat(schema 5.1.0): validate obs[cell_type_ontology_term_id]

schema/5.1.0/schema.md
=> Refreshed ontologies

cellxgene_schema_cli/cellxgene_schema/validate.py, cellxgene_schema_cli/tests/test_schema_compliance.py
- undo patch changes from #895
=> chore: roll back checks from patch

cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- change spacing and newlines to improve readability
- only a formatting change.
=> chore: fix spacing in schema_definition.yaml

scripts/migration_assistant/migration_template.jinja, scripts/migration_assistant/tests/test_convert_template.py
missed a few linting / test issues
=> fix: migration template updates for linting

schema/5.1.0/schema.md
=> updated curation instructions for column_colors

schema/5.2.0/schema.md
=> Added sci-RNA-seq3

schema/5.2.0/schema.md
=> updated requirements for development_stage_ontology_term_id

schema/5.2.0/schema.md
=> updated requirements for feature_length

schema/5.2.0/schema.md
=> updated anndata requirements

schema/5.2.0/schema.md, schema/5.2.0/seurat_encoding.md
=> added feature_type

cellxgene_schema_cli/requirements.txt, scripts/schema_bump_dry_run_ontologies/requirements.txt
- https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/cellxgene-ontology-guide/210
=> chore: bump COG version for schema 5.2

schema/5.2.0/schema.md, schema/5.2.0/seurat_encoding.md
=> approved schema

schema/drafts/5.2.1-experimental.md
=> Rename experimental schema and address feedback

cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml, cellxgene_schema_cli/tests/test_schema_compliance.py, schema/drafts/5.2.1-experimental.md
https://app.zenhub.com/workspaces/cs-platform-661fffc5c6339904f8f42cb2/issues/gh/chanzuckerberg/single-cell-curation/1050
validates that `development_stage_ontology_term_id` is an `FBdv` term
added unit tests
=> feat: validate development_stage_ontology_term_id for fruit fly

cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml, cellxgene_schema_cli/tests/test_schema_compliance.py, schema/drafts/5.2.1-experimental.md
https://app.zenhub.com/workspaces/cs-platform-661fffc5c6339904f8f42cb2/issues/gh/chanzuckerberg/single-cell-curation/1047
- adds fruit fly validation rules for `organism_tissue_ontology_term_id`
added unit testing
=> feat: fruit fly validation for organism_tissue_ontology_term_id

cellxgene_schema_cli/requirements.txt
- https://github.com/chanzuckerberg/single-cell-curation/issues/1096
- pin anndata to <0.11.0
- verify unit tests pass
A new release of the CLI will be needed after this PR merges.
=> fix: pin anndata to <0.11

schema/drafts/5.2.1-experimental.md, schema/drafts/5.3.0.md
=> removed strongly recommended from development stage

schema/drafts/5.2.1-experimental.md
=> Added c. elegans

cellxgene_schema_cli/tests/test_schema_compliance.py
- #1106 
- checks for visium descendant assay when checking requirement for X_{spatial}
=> feat: X_{suffix} to include descendants of Visium

schema/drafts/5.3.0.md
=> updated X matrix requirement

schema/drafts/5.3.0.md
=> Updated assay_ontology_term_id

schema/drafts/5.3.0.md
=> Updated genetic_ancestry

cellxgene_schema_cli/cellxgene_schema/validate.py, cellxgene_schema_cli/tests/test_schema_compliance.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/1209
- updates the genetic ancestry tolerance to 0.0002
added some basic unit tests for this
=> feat: update genetic ancestry tolerance

cellxgene_schema_cli/cellxgene_schema/validate.py, cellxgene_schema_cli/tests/test_schema_compliance.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/1257
as titled lol
n/a
=> fix: correct spelling of ontololgy

schema/5.3.0/schema.md
=> clarified fragment requirements

schema/5.3.0/schema.md
=> editorial updates for multiome

cellxgene_schema_cli/requirements.txt
- undoing an unfortunate dependabot suggested dask upgrade.
- revert to working dask version
=>  revert dask to 2024.12.0

schema/6.0.0/schema.md
=> Updated feature_name

schema/6.0.0/schema.md
=> Is filtered

schema/6.0.0/schema.md
=> Updated is_filtered

cellxgene_schema_cli/cellxgene_schema/validate.py, cellxgene_schema_cli/tests/test_validate.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/1076
- i updated the implementation of `_is_single` to handle both bools and numpy bool values. i also basically rewrote the entire function for better clarity
updated one of our existing tests to validate that everything works as expected. note that i wrote the tests before the code change, and before the code change the last test case `(np.bool_(False), np.bool_(True), False),` was failing but the normal boolean test case `(False, True, False),` was passing
=> feat: fix validation of is_primary_data to handle numpy bools

cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
https://czi-sci.slack.com/archives/C08MF1AJ6F5/p1747355527109409?thread_ts=1747337258.902249&cid=C08MF1AJ6F5
we had a suggestion to change the copy of the error message, so i've updated it here
n/a
=> chore: update copy of disease error msg

cellxgene_schema_cli/cellxgene_schema/migrate.py, cellxgene_schema_cli/cellxgene_schema/utils.py, cellxgene_schema_cli/cellxgene_schema/validate.py, cellxgene_schema_cli/tests/test_migrate.py, cellxgene_schema_cli/tests/test_schema.py, cellxgene_schema_cli/tests/test_schema_compliance.py, cellxgene_schema_cli/tests/test_utils.py
https://czi-sci.slack.com/archives/C08MF1AJ6F5/p1749222387913889
- seems like there are some legitimate cases where you would have all 0's, so we're downgrading this to a warning. i wrote up a ticket [here](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/759) to pull in all the datasets we raise these warnings on, so lattice can evaluate them and figure out what we want to do long term
updated tests as needed
=> feat: downgrade feature_is_filtered errors to to warning

schema/7.0.0/schema.md
=> updated ethnicity

cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml, cellxgene_schema_cli/tests/test_schema_compliance.py
https://czi.atlassian.net/browse/VC-3520?atlOrigin=eyJpIjoiZTFhNThiZDI2YzAxNDMzYWFhYmVjNTFhZGEwNjA5ZTciLCJwIjoiaiJ9
=> VC-3520 feat: schema 7.0 changes to suspension_type
