chanzuckerberg/single-cell-curation

- docs/gene_sets.md
- docs/gene_sets_example.csv
Closes #25
Additional requirements to be added per alignment with cellxgene explorer:
The cellxgene gene set data format is a Tidy CSV (comma-separated values) file using ~UTF-8~ ASCII encoding
cellxgene portal will warn and fail when the following illegal ASCII characters or sequences are detected in any **required** field value:
* control characters (decimal 0-31)
* DEL (decimal 127)
* leading spaces (decimal 32) in a field - `     This is an example`
* trailing spaces (decimal 32) in a field - `This is an example     ` 
* multiple spaces (decimal 32) "internal" to a field - `This     is an example`
> Gene Set Format documentation

- docs/corpora_schema.md
- docs/encodings/anndata_encoding.md
This PR describes a proposed schema change and encoding implementation of adding "batch" information to the schema. 
In brief, it is designed to enable a user to specify an arbitrary set of cell metadata fields that jointly describe the batch of each cell. These fields may or may not be part of the cellxgene schema. 
It addresses #2 .
> RFC: Add mandatory batch field to schema

- docs/corpora_schema.md
- docs/encodings/anndata_encoding.md
- docs/schema_guide.md
This PR updates the schema to:
* Check back in the anndata encoding, in `cellxgene-schema/docs/encodings/`
* Remove information that is specific to the AnnData encoding. This information was duplicative, there was no need to augment the encoding. 
* Add background on why one should read the schema document, the encoding, or the schema guide (to be replaced or augmented by the curation tutorial)
* Fix editorial issues
* Address comments from @brianraymor in #46
> Separate cellxgene schema and anndata encoding

- schema/2.0.0/corpora_schema.md
Introduces the optional `approximate_distribution` field to `uns`. 
Assumptions made by inserting this field in `uns` instead of `obs`: 
* Data in X are homogeneously distributed. This assumption currently makes sense since X holds a single data type. The data formats created by major toolchains recommend that different data types be stored in different matrix layers, so this will likely be the correct solution moving forward.
Assumptions made by creating a `str` typed field instead of `dict`: 
* cellxgene computes on only one matrix layer, and that data type is in X. If cellxgene expands to multi-modal data, we will need to change this field to enable users to describe each data modality. However a, `str` typed field is currently the correct choice. 
See …
> introduce `X_approximate_distribution`.

- schema/2.0.0/corpora_schema.md
At the heart of the issue is that we need to accommodate the schema for multi-organism datasets that use orthologous genes with either human or mouse ENSEMBL IDs. If we want IDs for more organisms we can discuss it in the future as needed.
This PR:
1. Changes cell requirements of adata.obs["organism_ontology_term_id"]  and allows any organism for cells.
2. Adds a cell requirement to adata.obs["development_stage_ontology_id"]  to allow for development stages of non-human and non-mouse cells.
3. Adds a gene requirement by adding a column to adata.var to indicate the source of the gene ID.
4. Clarifies text to state that we are taking cells from any organism so long as they are using orthologs in human or mouse.
This PR addresses:
- Dependencies of adata.obs["organism_ontology_term_id"]  and …
> Schema update to support multi-organism data

- schema/2.0.0/corpora_schema.md
Minor change that reduces the space of allowed organisms for cells. Instead of allowing for the entire tree of life, this revision only includes Metazoa organisms.
> Only allow for Metazoa organisms

- schema/2.0.0/corpora_schema.md
Per this [comment thread](https://github.com/chanzuckerberg/single-cell-curation/pull/116#discussion_r699680657), clarifying the requirements for `tissue_ontology_term_id` to ensure that validation can correctly enforce.
> Update requirements for tissue_ontology_term_id

- schema/2.0.0/schema.md
Updates links to the reference gene files. New versions: human gencode 38 and mouse gencode 27
Addresses the schema component of this:
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1404
> Update gene references in schema - human gencode 38 and mouse gencode 27

- cellxgene_schema_cli/CHANGELOG.md
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/setup.py
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
The validator was missing one check when validating the raw data:
- When both `adata.X` and `adata.raw.X` are present but `adata.raw.X` contains non-integer values, then a warning should be shown suggesting that data in `adata.raw.X` may not be raw.
A warning is preferred as opposed to an error as @jychien states:
> For the Pott gut demo dataset, they actually used STARsolo for their pipeline. I am not as familiar with data from STARsolo, and it looks like it handles multi-gene reads in a way different from cellranger, and possibly could result in non-integers depending on the parameter used (documentation). I think a warning would be good, in case we need to be more flexible and don't want to have to change the validator for different pipelines or assays. But I think we've come across …
> Add warning during raw data validation for when raw.X has non-integer values

- schema/2.0.0/schema.md
Closes #166
Do we also need more nuanced text related to when `var.index` and `var.raw.index` are present or not? For example, `var.raw.index` is NOT REQUIRED to be present in ATAC-seq datasets like _GABAergic neurons — An Atlas of Gene Regulatory Elements in Adult Mouse Cerebrum_.
> Change feature_id to index

- docs/release_process.md
~~This is a first draft of a release process to release new versions of the `cellxgene-schema` PyPI package. The process is very similar to the release process of [cellxgene Desktop](https://github.com/chanzuckerberg/cellxgene/blob/main/dev_docs/release_process.md) but with one notable exception. I have simplified the release process to exclude `rc` versions for now. Until burning of version numbers becomes a problem, I figured we can stick to just releasing to Test PyPI first and if we burn a version number there, we should note it and just use the next.~~
This is a draft of the release process to release new versions of the `cellxgene-schema` PyPI package that is pretty much identical to the release process of [cellxgene Desktop](https://github.com/chanzuckerberg/cellxgene/blob/main/dev_ …
> Initial draft of a release process for the cellxgene-schema PyPI package

- cellxgene_schema_cli/cellxgene_schema/cli.py
- cellxgene_schema_cli/cellxgene_schema/schema_definitions/2_0_0.yaml
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/setup.py
- cellxgene_schema_cli/tests/test_validate.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-curation/162
**Functional**
@pablo-gar 
@metakuni 
**Readability**
@ebezzi 
This commit issues warnings for AnnData matrices X and raw.X when either
of them is unable to be converted to Seurat due to size limitations. It
also returns the Seurat convertibility status to calls to
validate.validate in order to make the convertibility available to the
Data Portal.
> Warn when Seurat conversion will fail

- Makefile
The create-release-candidate make target was making use of the 'shell'
functionality in the Makefile language; the expansion for this
functionality was resulting in evaluation of the shell script
immediately at the beginning of the execution of the target's recipe,
which produced a logging bug and a bug in the naming of the rc branch
> Fix shell error in Makefile

- .gitignore
- cellxgene_schema_cli/cellxgene_schema/cli.py
Ticket: #2470 https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/2470
Move imports to after Click-argument validation to improve cli responsiveness.
Time to see help menu reduced from ~5s to ~0.1s.
Before:
```
(venv) ➜  cellxgene_schema_cli git:(main) ✗ L$ time PYTHONPATH=. python -m cellxgene_schema.cli validate
Usage: python -m cellxgene_schema.cli validate [OPTIONS] H5AD_FILE
Try 'python -m cellxgene_schema.cli validate -h' for help.
Error: Missing argument 'H5AD_FILE'.
PYTHONPATH=. python -m cellxgene_schema.cli validate 
**5.38s user 0.71s system 116% cpu 5.221 total**
```
After:
```
(venv) ➜  cellxgene_schema_cli git:(main) ✗ L$ time PYTHONPATH=. python -m cellxgene_schema.cli validate
Usage: python -m cellxgene_schema.cli validate …
```
> chore: improve cli responsiveness

- notebooks/compute_ancestor_mapping.ipynb
- ontology/compute_ancestor_mapping.ipynb
Notebook used to compute ancestors for nodes in human, mouse and UBERON (only a subset) ontologies.
> Add ontology ancestor mapping notebook

- .github/workflows/push_tests.yml
- Makefile
- cellxgene_schema_cli/requirements.txt
- readme.md
- Add Codecov badge to the top level repo README.
- Upload coverage report to Codecov in push_test Github Action.
- Alphabetize `requirements.txt`
- Run `coverage` instead of `pytest` to execute unit tests so that coverage stats are generated.
> Add support to generate metrics about testing coverage in schema CLI and upload to Codecov

- cellxgene_schema_cli/cellxgene_schema/cli.py
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/requirements.txt
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_validate.py
Add an `--ignore-labels` flag. If true, the validator will not check for reserved column names that would be added by the `--add-labels` option.
This is useful if you want to validate a dataset that has already been uploaded to the cellxgene data portal.
> feat: add --ignore-labels flag

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
Reject NaN values in curies. Normally, this shouldn't be needed as the curie validation will already catch this. If we do suffix stripping, though, it will break with the errors shown [at the beginning of this ticket](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-curation/211).
I believe this additional enforcement is desirable from a curator's perspective, even if it is more general than what was originally requested.
> feat: reject NaN values in curies

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
Note: this solves issue number 2 from the ticket.
> chore: remove ancestry-related errors if a term is in wrong ontology

- cellxgene_schema_cli/cellxgene_schema/convert.py
#262 
Achieves the following during the convert cli command:
If suspension_type column is already in obs, leave it in the object and report what the categories currently are for this column
If suspension_type is not present in obs, add suspension_type for assays that have only one possible value and report the value that was added
Else, if NaN was added for suspension_type, report this as well
> Add logging for suspension_type auto-assignment in cellxgene-schema convert command

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/3_0_0.yaml
- cellxgene_schema_cli/cellxgene_schema/validate.py
Fix bug where ValueError is thrown and validation terminates early when columns are unexpectedly non-string categoricals
> fix: add and validate fields that must be categorical strings

- cellxgene_schema_cli/cellxgene_schema/convert.py
- cellxgene_schema_cli/cellxgene_schema/schema_definitions/3_0_0.yaml
- cellxgene_schema_cli/tests/test_schema_compliance.py
- schema/3.0.0/schema.md
#343 
Changes:
- updated 3.0.0 OpenAPI spec rules to allow obs rows with Drop-seq assays to have either nucleus OR cell as suspension_type
- updated convert script to account for not being able to auto-assign suspension_type to Drop-seq obs rows anymore + updated logged message to more clearly explain workflow where auto-assignment cannot be done.
- updated schema def doc
- update tests
> fix: Update suspension_type validation rules for Drop-seq assays

- cellxgene_schema_cli/cellxgene_schema/validate.py
- datasets/biccn-bakken/scripts/reformat_seurat.R
- schema/3.0.0/schema.md
- schema/3.0.0/seurat_encoding.md
#[3290](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/3290)
> chore: update docs and logs to reference Seurat v4 instead of v3

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/3_0_0.yaml
- cellxgene_schema_cli/cellxgene_schema/validate.py
Fix for logging duplicate issue flagged [here](https://github.com/chanzuckerberg/single-cell-curation/issues/343#issuecomment-1254024727)
Changes:
- Changed default error message suffix for suspension_type (i.e. scenario where assay does not match one in the assay-suspension type table defined in the schema definition) to provide more context
- Skip check/error logging for null values in categorical fields, IF categorical field is also an enum. Having both checks is extraneous, since checking against enum values will also, inherently, flag and log null values. So far, only suspension_type is both an enum and categorical, so it should be the only field affected.
> fix: don't duplicate error logs about null entries on enum fields

- notebooks/curation_api/R/create_collection_R.ipynb
- notebooks/curation_api/R/create_dataset_R.ipynb
- notebooks/curation_api/R/create_revision_R.ipynb
- notebooks/curation_api/R/upload_local_datafile_to_dataset_R.ipynb
- notebooks/curation_api/python/create_dataset.ipynb
- notebooks/curation_api/python/src/collection.py
- notebooks/curation_api/python/src/dataset.py
- notebooks/curation_api/python/upload_local_datafile_to_dataset.ipynb
- notebooks/curation_api/python_raw/create_collection.ipynb
- notebooks/curation_api/python_raw/create_dataset.ipynb
- notebooks/curation_api/python_raw/create_revision.ipynb
- notebooks/curation_api/python_raw/upload_local_datafile_to_dataset.ipynb
- "revision_id" -> "id"
- "collection_id" -> "id"
- "dataset_id" -> "id"
> feat: standardize 'id' attribute usage

- notebooks/curation_api/R/get_dataset_assets_R.ipynb
- notebooks/curation_api/python/src/dataset.py
- notebooks/curation_api/python_raw/get_dataset_assets.ipynb
The assets array is no longer returned underneath a top-level '.assets' attribute
> feat: GET /assets returns array directly

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- cellxgene_schema_cli/tests/test_validate.py
Fixes #399
Primary change: significantly reduce memory use when validating CSR-formatted data. The `X` and `raw.X` are read incrementally, in chunks, dramatically reducing memory usage. Dense data is run in backed mode, and should also see reduced memory use. CSC is still loaded into memory as before, and has no change.
Changes:
* revise Validator() to use backed mode when reading AnnData
* incrementally compute over `X` and `raw.X`
* reformat validate.py to conform with repo Python style configuration
* clean up debt in tests related to Pandas and AnnData
Old and new code was compared:
* there is a slight performance penalty (less than 10%) for using backed mode on small to mid-sized datasets
* large CSR datasets now complete without an OOM failure (or excessive swapping).  This was …
> Use backed mode to read H5AD when validating

- notebooks/curation_api/R/create_collection_R.ipynb
- notebooks/curation_api/R/create_dataset_R.ipynb
- notebooks/curation_api/R/create_revision_R.ipynb
- notebooks/curation_api/python/example_workflow.ipynb
- notebooks/curation_api/python/src/collection.py
- notebooks/curation_api/python/src/dataset.py
- notebooks/curation_api/python_raw/create_collection.ipynb
- notebooks/curation_api/python_raw/create_dataset.ipynb
- notebooks/curation_api/python_raw/create_revision.ipynb
Changes:
- update id references in curator notebooks to reference explicit field names (collection_id, dataset_id)
- remove original_id usage (deprecated)
> chore: update curator notebooks for new explicit id field names and version ids

- cellxgene_schema_cli/cellxgene_schema/write_labels.py
- cellxgene_schema_cli/tests/test_validate.py
fixes #416 
- remove the copy of the anndata when writing labels. This is safe because the original dataset is open in read only mode. Any changes made to the datasets are only captured in memory. Those changes are then written out to a different files.
- add the stack trace to error collected when writing labels. This is to help debugging in the future.
- add missing tests
- add a test to verify the label h5ad is generated consistently. This is to verify that present and future changes don't accidentally change the labeled output file. 
Ran validation and wrote labels with this [raw.h5ad](https://s3.console.aws.amazon.com/s3/buckets/corpora-data-dev?region=us-west-2&prefix=00a3fb7e-cd16-4ea1-b7b3-5e915061ffe2) and was able to produce a new h5ad that had the has the same sha256 hash as …
> Don't copy the original anndata to write labels

- .github/workflows/ontology_bump_dry_run.yml
- .github/workflows/ontology_process.yml
- cellxgene_schema_cli/cellxgene_schema/ontology_files/owl_info.yml
Update all pinned ontologies (except HsapDv + MmusDv) to latest releases, for demo purposes.
> demo: end-to-end ontology curator report workflow

- cellxgene_schema_cli/scripts/ontology_processing.py
- schema_bump_dry_run_scripts/ontologies/ontology_bump_dry_run.py
- schema_bump_dry_run_scripts/tests/fixtures/with_replaced_by_diff_ontology_expected
- schema_bump_dry_run_scripts/tests/fixtures/with_replaced_by_expected
- schema_bump_dry_run_scripts/tests/test_ontology_bump_dry_run.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4837
- Standardize all 'replaced_by' fields using the format "<term>:<ID>" during ontology file processing
- Update dry run script to parse replaced_by prefix term using consistent delimiter ":", defined in processing file
- Reprocess ontology file to pick up standardized replaced_by's
> feat: standardize format of 'replaced_by' field in all_ontology.json

- cellxgene_schema_cli/scripts/gene_processing.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4814
- Output diff file will live where processed ontology files live. The 'migrate' script that will automate the 'Lattice Algorithm' for removing deprecated terms will be part of the cellxgene_schema_cli package as well.
- Only accounts for gene IDs that were 'deprecated' (i.e. ID appeared previously, no longer appears in new reference files). It does not detect IDs that changed
> feat: generate diff between gencode releases when processing new GENCODE files

- schema_bump_dry_run_scripts/ontologies/ontology_bump_dry_run.py
- schema_bump_dry_run_scripts/tests/fixtures/group_datasets_by_collection_expected
- schema_bump_dry_run_scripts/tests/fixtures/with_comments_and_considers_expected
- schema_bump_dry_run_scripts/tests/fixtures/with_replaced_by_expected
- schema_bump_dry_run_scripts/tests/test_ontology_bump_dry_run.py
- Decompose parsing into 1) a mapping function that runs the logic to detect deprecated terms + maps reporting data by collection ID and deprecated term, and 2) a function that iterates over the map and writes to the output file in the desired format
- Update writing logic to remove Dataset ID + replace with count of affected datasets in Collection for the detected deprecated term
> feat: update curation report to group reporting deprecated terms in datasets from the same collection

- .bumpversion.cfg
- .github/workflows/publish-to-pypi.yml
- cellxgene_schema_cli/setup.py
- Set up to release new minor version to Test PyPI and PyPI when there are ontology/GENCODE reference file bumps in main
- For now, setting it to release as a release candidate for testing, and only to test PyPI. Will change once ready to bump in prod
- Added Test PyPI / PyPI API keys to Github secrets
- Test PyPI 3.1.0rc0 published release: https://test.pypi.org/project/cellxgene-schema/3.1.0rc0/
- Action triggering release above: https://github.com/chanzuckerberg/single-cell-curation/actions/runs/5125586931
> feat: release cellxgene-schema to test pypi

- schema_bump_dry_run_scripts/genes/requirements.txt
Fixes seg faults on gencode dry run updates
> chore: update tiledb to 0.21.4 to match data-portal

- cellxgene_schema_cli/scripts/ontology_processing.py
- cellxgene_schema_cli/tests/test_utils.py
- scripts/schema_bump_dry_run_ontologies/ontology_bump_dry_run.py
- scripts/schema_bump_dry_run_ontologies/tests/fixtures/group_datasets_by_collection_expected
- scripts/schema_bump_dry_run_ontologies/tests/fixtures/with_replaced_by_diff_ontology_expected
- scripts/schema_bump_dry_run_ontologies/tests/fixtures/with_replaced_by_expected
- scripts/schema_bump_dry_run_ontologies/tests/test_ontology_bump_dry_run.py
Issue: #533 
Changes:
- Will store comments for all deprecated entries in all_ontology json during ontology processing, and write them to curator report for all deprecated terms in the corpus (previously, we were skipping them on terms with replaced_by's)
> fix: include comments in all curator report entries

- notebooks/curation_api/python/get_dataset.ipynb
- notebooks/curation_api/python/get_dataset_version.ipynb
See issue - I'm just setting the default version of the notebooks to actually download the associated assets after performing the `GET` call for the metadata
> fix: asset downloads for python/get_dataset_version.ipynb

- cellxgene_schema_cli/cellxgene_schema/migrate.py
- cellxgene_schema_cli/cellxgene_schema/remove_labels.py
- cellxgene_schema_cli/cellxgene_schema/utils.py
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/cellxgene_schema/write_labels.py
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_migrate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- scripts/migration_assistant/migration_template.jinja
- scripts/migration_assistant/tests/test_convert_template.py
- modify migration template to move DEPRECATED_FEATURE_IDS and ONTOLOGY_TERM_MAPS to outside of the migrate function. This makes testing migrate easier, by allowing us to mock these variables easily.
- Add test h5ad for migration testing.
- extract common functions in validate.py to utils.py
- load h5ad to memory if it has raw and DEPRECATED_FEATURE_IDS.
- Move
> fix(schema-migrate): add tests for migrate.py

- .github/workflows/minor-schema-version-bump.yml
- .github/workflows/trigger-schema-migration.yml
- cellxgene_schema_cli/cellxgene_schema/utils.py
- cellxgene_schema_cli/tests/test_utils.py
- scripts/compute_mappings/requirements.txt
- Fresh install of cellxgene_schema_cli requirements to ensure latest version is downloaded for test step after upload (if not, dependency resolver could try to install previous version to avoid conflicting dependencies) 
- add --ignore-unmatch flag to git rm *_diff files, to avoid error when no _diff files (i.e. no GENCODE update) exists 
- Update awscli pinned version for compute_mappings step (known error found in nested dependency)
- Add Jason's util function for migrate PRs
- Move push tags step until after we validate pypi upload
> fix: automation bugs

- schema/4.0.0/schema.md
Closes #334 
@jahilton @pablo-gar @bkmartinjr 
This PR includes the following changes since the previous reviewed draft.
1. It adopts Bruce's suggestion to only allow comma separation and not comma+space separation. Commas are now a _safe_ delimiter because the one term with a comma in its label has been updated. I've requested that no commas are used for future labels.
1. It enforces an order for categoricals and consistent downstream consumption. While I preferred ordering by labels, it's less complex to order by HANCESTRO terms, although more curation is required . My main sticking point was the need to reorder BOTH self_reported_ethnicity_ontology_term_id and self_reported_ethnicity_ontology_term_id_colors (if present). And IF the value of the ontology terms were not ordered, then the …
> Updated self reported ethnicities

- .github/workflows/minor-schema-version-bump.yml
Now the reviewers that are set when minor-schema-version-bump.yml can be changed using github variables. Before a new PR was required to modify this value.
> feat(migrate): set migrate reviewers

- .github/workflows/close-inactive-prs.yml
As we move to CI/CD, some automation can help ensure that we're working towards trunk-based development and ensuring that non-draft PRs don't stay open too long without some movement. Ideally, this Github Action helps us with a few things:
1. PRs remain small so that they can be reviewed quickly and merged.
2. If a PR has be alive for more than 2 weeks, updates are required so that there is visibility as to why the PR is blocked. 
3. If the PR has to be alive for more than 2 weeks and is blocked, it reverts to being a draft PR or closed.
No ticket.
Add a Github Action that runs daily. Each day all active (non-draft) PRs older than 2 weeks are marked with a stale tag and a warning comment is made to update the PR. In another 3 days (3 days was chosen to accommodate long weekends + 1 day), …
> feat: Add a Github Action that automatically closes stale PRs.

- .github/workflows/close-inactive-prs.yml
The default setting for the Github Action to automatically mark PRs as stale sets issues as `stale` after 60 days. This PR fixes that by overriding the default to -1 which ensures that issues are never marked as stale.
#560 
None.
None.
The `close-inactive-prs` Github Action has been modified to never set issues as stale.
Not tested.
None.
> fix: override default so that issues are not marked as stale

- cellxgene_schema_cli/cellxgene_schema/utils.py
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_validate.py
I factored out the dimension attribute access so that testing could make use of `unittest.mock.patch`; the AnnData object appears to be somewhat resistant to my attempts to edit the actual `.raw.X` and `.raw.var`.
> feat: validate raw matrix does not have more genes than raw var

- cellxgene_schema_cli/cellxgene_schema/env.py
- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/cellxgene_schema/write_labels.py
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
#518 
Changes:
- add schema_reference as reserved column in 'uns' for validation
- populate schema_reference field during add-labels step
> feat: add schema_reference field to uns during add-labels

- cellxgene_schema_cli/cellxgene_schema/ontology.py
- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/cellxgene_schema/write_labels.py
- cellxgene_schema_cli/tests/fixtures/examples_ontology_test.py
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_ontology.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- cellxgene_schema_cli/tests/test_validate.py
#516 
Changes:
- annotate feature_length field in add-labels function, based on feature_id and pre-computed gene info CSV files (derived + committed to repo during ontology bumps). Set to 0 for non-gene features (even though a length is calculated + available for spike-in controls) 
- refactor gene ontology tool that fetches info from gene CSV files to accommodate fetching calculated feature_length 
- update tests
> feat: add feature length field, annotated by add-labels function

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_validate.py
- #382
- remove `max_values_to_check`  from `Validator._is_raw`
- Add unit test for the `Validator._is_raw`
- Used [memory_profiler](https://pypi.org/project/memory-profiler/) to verify memory usuage does not explode with this change. A 1,395,601 cell dataset used <5GB of memory. The original size of the file was 50GB.
1. Download the dataset: [Whole Taxonomy - DLPFC: Seattle Alzheimer's Disease Atlas (SEA-AD)](https://cellxgene.cziscience.com/collections/1ca90a2d-2943-483d-b678-b809bf464c30)
1. run `make install` to install the local cellxgene_schema version.
3. `run pip install memory_profiler`
4. *test.py* 
```python
import anndata
from cellxgene_schema.validate import Validator
from memory_profiler import profile
def test():
func = profile(validator._is_raw)
func()
if __name__ == …
```
> feat(4.0): Remove 5000 cell limit for raw validation

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- #514 
- See error message formatting feedback from Jason: https://github.com/chanzuckerberg/single-cell-curation/issues/514#issuecomment-1728200255
- If we're only validating an ontology term against 1 allowed ancestor, print the ancestor term we're checking for in the error message as single term with single quotes instead of a list of 1. 
- For scenarios where a list of ancestors is expected, print as a single concatenated list rather than a list of lists
- unit tests
> fix: clean-up error message if only 1 ancestor is valid for ontology term

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
https://github.com/chanzuckerberg/single-cell-curation/issues/590
- fixes some of the issues caught by @jahilton:
- only fail if all values are NaN, not if any values are NaN
- having NaN should not result in the infinity error message getting picked up
- validate that suffixes are at least one character
- validate that keys don't have whitespace
- gracefully fail if values have strings, aka don't fail on the `isinf` call
- adds test coverage for all of the new validation things added
version at …
> feat: fix X_{suffix} validation and add test coverage

- cellxgene_schema_cli/cellxgene_schema/utils.py
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_utils.py
- #581
- Update read_h5ad to read into memory if to_memory is True
- Add supporting unit tests
- run the unit tests
> feat(4.0): Load into memory if add_labels_file != None

- .github/workflows/minor-schema-version-bump.yml
- .github/workflows/trigger-schema-migration.yml
- https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/573
- Required to not auto-dispatch major schema version updates (otherwise, we will be forced to schedule and enforce ontology/gene reference file bumps as the last update we make to major schema version updates, lest we trigger the bump workflow prematurely)
- trigger workflows related to dry-run, pypi publish, migrate PR creation, batch job run manually rather than on updates to specific files (we might want to update these files without accidentally triggering these workflows)
- N/A, github action syntax for this operation is well-documented and testing would require triggering workflow steps we don't want to run
> chore: update schema workflows to run on manual dispatch rather than auto-triggers

- cellxgene_schema_cli/cellxgene_schema/validate.py
- #418 
- Simple change in the error message that is produced when the # of vars in raw.X does not exactly equal the number of vars in raw.var
```
```
> fix: improve error message when raw.X and raw.var are mismatched

- cellxgene_schema_cli/cellxgene_schema/ontology_files/owl_info.yml
- cellxgene_schema_cli/tests/fixtures/examples_ontology_test.py
Introduced pinned links for these two ontologies. Additionally, fix a unit test that began failing after previous ontology update by updating a hard-coded value in the test fixtures.
- #616 
```
```
> fix: pin HsapDv and MmusDv

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- based on feedback [here](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/513) and [here](https://github.com/chanzuckerberg/single-cell-curation/pull/625#discussion_r1337632953), it looks like we should only do validation on these fields if the key is specified in `uns`
- updating the validation to only run the validation on the colors fields if the key is set and the value is not an empty array
- added a test to verify that if `uns["suspension_colors"]` is removed, we'll still pass validation
> fix: only validate colors if the key is specified

- cellxgene_schema_cli/tests/test_schema_compliance.py
DRY up the error message testing code
- put error message suffix in a helper function
> refactor: move common error message language into helper function

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- #519 
- If the reason for this PR's code changes are not clear in the issue, state value/impact
- Add citation as a reserved column for uns
- Add label to test data uns object
```
```
> feat: add 'citation' as a reserved_column on uns

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/cellxgene_schema/validate.py
Changes: 
- Fixed confusing state where marking a component 'required: null' in the schema definition yaml meant that it IS required. Use boolean instead
- Updated checks in validate.py that use this attribute accordingly
> chore: refactor confusing 'required' attribute in schema_definition.yaml

- cellxgene_schema_cli/cellxgene_schema/utils.py
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_validate.py
- 'format' is a built-in Python function; avoid shadowing this
- corrects one bug where an assert was testing against this built-in `format` because the previous appearances of the variable were already named `matrix_format`
> fix: rename all instances of 'format' variable to 'matrix_format'

- cellxgene_schema_cli/tests/test_validate.py
- Eventually this test and check will no longer be needed after upgrading to anndata 0.10.0+. This add a check if the bug is fixed and if the related check can be removed. 
- add write_h5ad to tests if the anndata write error still exists.
- updated unit tests
> fix: attempt to write bad dataset as part of the write tests

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
After lots of discussion on this ticket: https://github.com/chanzuckerberg/single-cell-curation/issues/590 we've decided that we want to validate that all obsm keys start with the `X_` suffix, but only raise a warning. If an embedding key doesn't start with `X_` and also has other validation failures (ex: not an array), we would want to surface all of these but as warnings.
- We check to see if an obsm key starts with `X_`. If not, we raise a warning that the key doesn't start with `X_`.
- Run all subsequent validations against the key, but raise a warning if it doesn't start with `X_` and an error if it does start with `X_`
- I'm keeping the requirement that at least one obsm key must start with `X_` to raise a validation error if there are no valid obsm keys
added a new test …
> feat: verify all obsm keys start with X_ suffix

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- #614 
- Fix bug introduced in previous PR for this issue
- check that number of nonzero rows in a matrix chunk equals matrix chunk size rather than full matrix size
- small fix to DRY up code when fetching raw matrix in has_valid_raw
- added test
- unit tests
> fix(raw matrix validation): compare number of nonzero rows in matrix chunk against matrix chunk size, not full matrix size

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
https://github.com/chanzuckerberg/single-cell-curation/issues/590
per discussion here: https://github.com/chanzuckerberg/single-cell-curation/pull/654#discussion_r1346503528
updating the whitespace error to only apply to `X_` prefixed embedding keys. raises a warning otherwise
updated the `test_obsm_key_name_whitespace` test
> fix: whitespace rule with X_{suffix}

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- https://github.com/chanzuckerberg/single-cell-curation/issues/513
based on QA feedback, added the following changes:
- validates that `{column}_colors` must be a numpy array
- verify that a corresponding categorical column in `obs` must exist
- verifies that none of the colors are non-strings, None, or numpy.nan
- verifies that all colors must be CSS4 colors or they must all be hex colors. no mixing allowed.
- filters out any duplicate colors, and raises an error if there are not enough unique colors to be found
- wrote a bunch of tests to verify all of those things ^
> feat: add more colors validation rules

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- based on discussion [here](https://github.com/chanzuckerberg/single-cell-curation/issues/513), we should be considering the obs column's dtype directly, instead of what we currently do, which is checking the schema def
- check for categorical obs column by looking at the column's dtype instead of the column definition
- wrote a test case where we have a new categorical column added to `obs[test_column]` that's not part of the schema def, and has valid colors in `uns[test_column_colors]`. this should pass validation, despite the column not existing in the schema def
> feat: update how we check for existing obs categorical columns

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/requirements.txt
- cellxgene_schema_cli/tests/test_schema_compliance.py
based on discussion [here](https://github.com/chanzuckerberg/single-cell-curation/issues/513), it seems like there are two changes to be made:
1. use `matplotlib` for CSS4 colors instead of a hard-coded list which could be outdated (or just incorrect, not sure)
2. duplicate colors should be allowed
- use `matplotlib` to determine CSS4 colors instead of using a hard-coded list
- allow duplicate colors
- i also removed the `_validate_hex_color` and `_validate_css4_color` functions, since these can both be one-liners now that we're removing the hard-coded list of color strings and that the `isinstance(color, str)` check is redundant since we do that in step 3 of the colors validation
added a test with colors set to `[lightgrey, lightgrey]` to verify that duplicate colors are allowed and that …
> fix: allow duplicate colors and use matplotlib for css4 named colors

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
https://github.com/chanzuckerberg/single-cell-curation/issues/513
- Currently, if a schema portal field is used in colors: "ERROR: Colors field uns[cell_type_colors] does not have a corresponding categorical field in obs." This PR adds on: "Annotate cell_type_ontology_term_id_colors instead."
added a test for above behavior
> feat: add note to annotate ontology term id field instead

- pyproject.toml
ignores files within `scripts/compute_mappings/tests`. i ran mypy against dan's branch `dan/555-compute-scripts` and verified the errors on test files were ignored
> feat: ignore test files within the scripts package

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_validate.py
- during schema migration 4.0 additional categorical type combinations were found to be invalid. This PR add additional test coverage and check for those error types.
- related to https://github.com/chanzuckerberg/single-cell-curation/issues/405
- add check for mixedd categorical types
- add check for illegal categorical types
- Add test to verify categorical types allowed.
- unit tests.
> fix: restrict allow categorical types

- cellxgene_schema_cli/cellxgene_schema/migrate.py
- added ontology term replacements corpus-wide for 3 terms we are now denying in schema 4 but are currently found in the corpus, per discussion in single-cell-four with Jason
- added check for datasets with RNA assays to meet new schema requirements--if raw matrix dtype is not np.float32 and the matrix values can be coerced safely into np.float32, do so and report the change as an output of the migration script (the migration SFM uses the output to report to slack in the curator report, mapping to the dataset_id and collection_id)
- Because the validator already enforces that raw matrix values for RNA assays are positive integers, we don't have to worry about floating point precision being lost. The only concern for safe casting is whether any values are too large to be represented as …
> fix: add necessary corpus transformations uncovered by dev migration

- .github/workflows/update-ontology-mappings.yml
- Part of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/616
- Extracted update ontology mappings job into its own standalone GHA that can be triggered manually, so it can be run outside of migration in case the scripts need to be updated + run + deployed outside a migration cycle
- Ran a test from this branch, the GHA ran as expected and kicked off a PR in the data-portal repo with the changes as expected.
> chore: create standalone gha for updating ontology mappings powering dp fe filters

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6340
- raises an error if either the obsm embedding key starts with a non-letter, or if it begins with X_ and the suffix starts with a non-letter
- added some unit tests to verify that this works as expected
> feat: validate obsm embeddings start with letter

- .github/workflows/gencode-bump-dry-run.yml
- .github/workflows/ontology-bump-dry-run.yml
- https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6394
- Create 1 standalone GHA job each for running ontology and gencode bump dry run reports, for flexibility in discovery phases of migration bumps (can see impact of file bumps in branches before merging in changes)
- Run dry run GHAs after merge
> chore: create standalone GHAs for running dry run reports for bumped schema ref files

- scripts/schema_bump_dry_run_ontologies/ontology_bump_dry_run.py
- scripts/schema_bump_dry_run_ontologies/tests/fixtures/with_comma_delimited_onto_id_list_expected
- scripts/schema_bump_dry_run_ontologies/tests/test_ontology_bump_dry_run.py
- Self-reported ethnicity ontology terms can now be made up of multiple, comma-delimited terms in a single ontology term entry. We need to account for this format while parsing ontology terms for the ontology report dry run (bug discovered after triggering dry run [reports](https://github.com/chanzuckerberg/single-cell-curation/actions/runs/7387333028/job/20095967802) in advance of bumping GENCODE for schema 4.1)
- Parse for comma-delimited lists of terms when processing ontology term entries, and perform deprecated term reporting for each term in list. Only applies to self-reported ethnicity, but done generally in case we adopt this format for other ontology types in the future (for now, we expect every other ontology type will yield lists of 1 when split by ",")
- get a successful …
> fix(ontology dry run): account for self-reported ethinicity listing comma-delimited ontology terms in one entry

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/tests/test_schema_compliance.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/719
validates that the `disease_ontology_term_id` is one of:
- PATO:0000461
- child of MONDO:0000001
- self or child of MONDO:0021178
added unit tests!
> feat: update validator for disease_ontology_term_id

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/tests/test_schema_compliance.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/717
- removes EFO:0002772 and EFO:0010183 as valid terms for `assay_ontology_term_id`. child / descendent terms are still valid
added unit tests!
> feat: update assay_ontology_term_id validation

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- #729 
- Raise `ValueError` if any duplicate column names appear in `var` or `obs` 
- Must `raise` rather than including in errors list because otherwise subsequent steps choke on `dtype` vs `dtypes` (originally [noted](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/627) by @Jchaffer787) 
- This pattern for such cases follows convention already loosely established in the validator code
- Unit tested
- Specific error message tested & confirmed via manual install 
```
```
> feat: column names must be unique within 'var' and 'obs' DataFrames

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/728
- Validates that uns values cannot be empty arrays, dictionaries, or strings
- Wrote unit tests to make sure error is raised for various types of zero-length values
> feat: Validate that uns array values are all > 0 in length

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_migrate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- schema/4.1.0/schema.md
- scripts/migration_assistant/tests/test_convert_template.py
- add exception for "unknown" to schema def yml
- update test_convert_template.py
- migrate script should get auto-updated during migration workflow
- #735 
- Permit `"unknown"` for `cell_type_ontology_term_id`
- Annotate `cell_type` as `"unknown"`
- Permit `"unknown"` for `tissue_ontology_term_id` when `tissue_type` is `"cell culture"`
- Annotate `tissue` as `"unknown"`
- Various unrelated typo fixes
- Fix test `unmigrated_X` in `examples_validate.py` to reference correct obs df shape as source of row count when instantiating
- unit tests added to test against scenarios where the ontology term for cell type or tissue is `"unknown"`
- test label writes
```
```
> feat: deprecate CL:0000003 'native cell' and replace with "unknown"

- cellxgene_schema_cli/tests/fixtures/examples_ontology_test.py
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- cellxgene_schema_cli/tests/test_validate.py
addresses https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/739
fixes any tests that were broken with the gencode version bump. it looks like some genes were renamed, so we had to update some of our test fixtures.
for the ontology tests involving deduplicated genes, these had to be rewritten because it seems like a lot of the deduplicated names were changed with the gencode bump. i identified deduplicated genes by adding this ✨ print statement ✨ to `process_gene_infos` in `gene_processing.py`:
```
def process_gene_infos(self, gene_infos: dict) -> None:
for gene_info_key in gene_infos:
self.process_individual_gene_info(gene_infos[gene_info_key])
print("Deduplicating gene names...")
gene_names = set()
duplicated_gene_names = …
```
> fix: test fixtures involving new gene info

- scripts/compute_mappings/compute_tissue_and_cell_type_mappings.py
fixes CL_0002494 from cell class to cell subclass https://czi-sci.slack.com/archives/C023Q1APASK/p1708047974696449?thread_ts=1707952513.995039&cid=C023Q1APASK
> fix: CL_0002494 cell subclass term

- cellxgene_schema_cli/cellxgene_schema/migrate.py
- #784 
- The auto-assigned remapping value for the to-be-deprecated `native cell` term `CL:0000003` was going to be `cell` `CL:0000000`. But per our [Schema 5.0 changes](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.0.0/schema.md#cell_type_ontology_term_id), this should be mapped to `unknown` instead. Additionally, Jason requests that we map `CL:0002371` to `unknown`.
- Reorder steps: make sure to remap GENCODE ids _before_ removing deprecated ids.
version at HEAD of …
> chore: add Schema 5.0 migration mappings, automated and from Lattice

- cellxgene_schema_cli/cellxgene_schema/migrate.py
- Addresses part of #797
- Update migrate script to change the offending `obsm` key that includes a `.` in the 2 str index position.
```
```
> chore: remove '.' from third position in obsm key

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/685
updates regex pattern from `r"^[a-zA-Z][a-zA-Z0-9]*$"` to `r"^[a-zA-Z][a-zA-Z0-9_.-]*$"` which in english means:
- first character must be alphabetic
- subsequent characters must be alphanumeric or one of `_`, `-`, `.` 
i wrote this script locally to figure out the list of all obsm keys that failed validation on the recent dev run:
```
import json
import re
def main():
with open("validation_errors.json", "r") as file:
json_data = json.load(file)
all_errors = []
for _, datasets in json_data.items():
for _, errors in datasets.items():
all_errors.extend(errors)
for error in all_errors:
prefix = "ERROR: Suffix for embedding key in 'adata.obsm' "
if error.startswith(prefix): …
```
> feat: update regex pattern and add valid test

- schema/5.0.0/schema.md
- schema/5.1.0/schema.md
https://github.com/chanzuckerberg/single-cell-curation/issues/797
After [discussion](https://czi-sci.slack.com/archives/C06AVGFV222/p1709754992082549), we agreed that it was best to validate that suffix keys matched the pattern `^[a-zA-Z][a-zA-Z0-9_.-]*$`
- Updates the schema requirements to match the new regex pattern
n/a
> chore: update schema requirements for obsm suffix keys

- cellxgene_schema_cli/cellxgene_schema/migrate.py
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
we have datasets with `adata.uns["log1p"] = numpy.bool_(True)`, so our check for `type(value) is not bool` doesn't work. for some reason, i can't directly connect this PR to this issue: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/728 but it does patch our previous work on that ticket, in addition to this one: https://github.com/chanzuckerberg/single-cell/issues/684
updates to also verify that `type(value)` is not `np.bool_` in both the migrate script and the schema validation
added unit test coverage
> fix: bool check for uns empty keys

- cellxgene_schema_cli/cellxgene_schema/migrate.py
- When an `obsm` key is the value for `uns["default_embedding"]`, then we need to update that value if that particular `obsm` key needed to be transformed due to the presence of illegal characters, otherwise validation fails.
- 
```
```
> chore: migrate: change uns default embedding where appropriate

- .github/workflows/generate-conversion-script.yml
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6863
- removes the version bump from the generate conversion script workflow
n/a
> chore: remove version bump from generate conversion script

- cellxgene_schema_cli/cellxgene_schema/convert.py
- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/scripts/ontology_processing.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- schema/5.1.0/schema.md
- #742
In 1) code, and 2) error messages:
- Replace `child` with `descendant` where appropriate
- Replace `children` with `descendants` where appropriate
I do not see any cases of function name changes that would be used via import in other repos (the one function whose name has been changed is prefaced with an underscore)
- Unit tests updated accordingly
```
```
> fix: use 'descendant' descriptor instead of 'child'

- .github/workflows/schema-version-bump.yml
- [single-cell #545](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/545)
- Remove the intermediate publish-to-PyPi step from schema version bump workflow
- Tested minor/major bump locally ✅ 
```
```
> feat: remove intermediate pypi publish from schema version bump

- scripts/check_corpus_dataset_schemas.py
This script can be used to survey the schema versions represented in the corpus, either public or private, by querying the Discover API. Useful for gaining visibility into corpus status during migrations.
- [single-cell-data-portal 6395](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6395)
- 
```
pip install git+https://github.com/chanzuckerberg/single-cell-curation/@main#subdirectory=cellxgene_s …
```
> chore: add dataset schema version check script

- .github/workflows/trigger-schema-migration.yml
- [single-cell-data-portal #6886](https://github.com/chanzuckerberg/single-cell-data-portal/issues/6886)
- pin trigger-schema-migration workflow python version to 3.11
```
```
> fix: pin python in schema migration workflow

- .github/workflows/trigger-schema-migration.yml
- [single-cell 547](https://github.com/chanzuckerberg/single-cell/issues/547)
- extract package version from setup
- for both Test PyPI and PyPI, add loops that wait until the just-published version is available
- [Tested on a modified workflow run](https://github.com/chanzuckerberg/single-cell-curation/actions/runs/8623232599) which printed the version and successfully passed through the `while` loop checking for the version via `pip index versions` call
```
```
> chore: address race condition with pypi publish in schema migration

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- cellxgene_schema_cli/tests/test_validate.py
- #827 
- Added `_check_spatial()` to validate `uns["spatial"]` values.
- Added Seurat conversion warning for Visium datasets.
- Added unit tests.
- Tested with 5.1.0 datasets.
> feat(schema 5.1.0): validate uns[spatial]

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- cellxgene_schema_cli/tests/test_validate.py
- #806 
- Update validate_obsm to account for new obsm['spatial'] embedding rules (see ticket)
- validating value of 'spatial' embedding is already covered by existing code in validate_obsm because they mirror validation for X_{suffix} embeddings; just had to add an elif conditional to make sure the checks are marked as 'error' if they fail, rather than 'warning' (previous behavior for non-X prefixed embeddings). Updated tests for these checks to pass in "spatial" as well as "X_{suffix}" to ensure coverage
- Update warning msg in validate_obsm about obsm embeddings without the "X_" prefix not appearing in Explorer. "spatial" embedding key WILL appear in Explorer despite not having an X_ prefix. So far, this is the only supported case for non X_ prefixed obsm embedding keys appearing in …
> feat: cellxgene-schema CLI must add validation for obsm['spatial']

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- cellxgene_schema_cli/tests/test_validate.py
- #829 
- Updated `_check_spatial` to sequence spatial-specific checks.
- Moved existing `_check_spatial` functionality to `_check_spatial_uns`.
- Added `_check_spatial_obs`. 
- Added unit tests.
- Tested with 5.1.0 datasets.
> feat(schema 5.1.0): validate obs[array_col], obs[array_row] and obs[in_tissue]

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- #853
- https://github.com/chanzuckerberg/single-cell-curation/pull/860
- change warning to an error when obsm field is not type numpy.ndarray.
- validating that obsm ndarray that don't match spatial or X_ must have a column length of at least 1.
- split out the checks in `_validate_obsm` to make it clear why an error occured.
- Update the unit tests to match expect behavior
- Added a test for unknown obsm keys
> fix(schema 5.1.0): throw error if obsm is not type np.ndarray

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- cellxgene_schema_cli/tests/test_validate.py
- #828
- refactor _has_valid_raw to split raw data validation into two branches: validating visium assay datasets with is_single True and in_tissue 0 values (introduces totally new validation rule that requires row-by-row iteration: rows in the matrix corresponding to `obs['in_tissue'] == 0` rows CAN be all zeros--as long as there is at least ONE non-zero value among the group of in_tissue == 0 rows)
- I chose not to introduce matrix chunking to the visium + is_single + in_tissue 0 data validation branch because we previously validate that its length is 4992 exactly, which is less than our default chunking size. Memory shouldn't be a concern in this case 
- moved typical data validation pathway for all other cases to _validate_raw_data method
- this includes datasets where visium + …
> feat: update X matrix validation to validate Visium assays

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_validate.py
- #862
- assert the `uns['spatial]`, `uns['spatial'][library_id]["scalefactors"]`, and `uns['spatial'][library_id]["images"]` or type `dict`.
- updated tests cases with new error messages and added additional test cases to verify new functionality.
> fix(5.1.0): type check for spatial and nested values

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_validate.py
- #862 
- add acheck that uns["spatial"][library_id] is dict
- add new unit test
> fix: check type of uns["spatial"][library_id] is dict

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_validate.py
- #873 
- Added unique constraint to assay ontology term id for spatial assay.
- Refactored calls to `_validate_spatial_tissue_position(tissue_position_name...` into separate function for testability.
- Added/updated unit tests.
> feat(schema 5.1.0): unique spatial assay ontology term id

- notebooks/curation_api/python/get_datasets.ipynb
- #857 
- Updated `get_datasets` notebook to include usage of `api_key_file_path` as well as the corresponding markdown.
> fix: api_key_file_path for get_datasets

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_validate.py
Anndata has a special class `SparseDataset` when loading a file to memory to reduce memory consumption. Unfortunately the data we need is not accesible from that class and needs to be loaded into memory before performing spatial validation, otherwise the following error occurs. 
```
Traceback (most recent call last):
File "/Users/ngloria/code/single-cell-curation/venv/bin/cellxgene-schema", line 8, in <module>
sys.exit(schema_cli())
File "/Users/ngloria/code/single-cell-curation/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/Users/ngloria/code/single-cell-curation/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/Users/ngloria/code/single-cell-curation/venv/lib/python3.10/site …
```
> fix: load SparseDatasets into memory

- scripts/migration_assistant/generate_script.py
- scripts/migration_assistant/migration_template.jinja
- scripts/migration_assistant/tests/test_convert_template.py
- See failing tests / lint in https://github.com/chanzuckerberg/single-cell-curation/actions/runs/9117090874/job/25067180453?pr=913
- add GENCODE_MAPPER, newly added and tested for in migrate.py for 5.0.0, as default empty map defined in migration_template  even if no GENCODE changes occurred (to fulfill tests written for it)
- keep trailing newline when generating migration script, to satisfy linting in auto-generated migrate script
> fix: update migration_template for linting and generate_script.py to add GENCODE_MAPPER

- .github/dependabot.yml
- scripts/migration_assistant/requirements.txt
- scripts/schema_bump_dry_run_genes/requirements.txt
adjusting the dependabot settings to avoid commit to pre-major versions which may include breaking changes.
- treat anndata and tiledb special because they don't have a major release and they need special consideration before upgrading.
- remove pyarrow requirement because it is unused in the actual code.
> chore: dependabot tuning

- cellxgene_schema_cli/cellxgene_schema/write_labels.py
- this is a minor cleanup 
- use getattr_anndata to fetch components. This recycles existing logic and avoid special if conditions.
> fix: use getattr_anndata instead of __dict__

- scripts/schema_bump_dry_run_ontologies/ontology_bump_dry_run.py
- ontology dry run was pinned to reading schema 5.0.0 ontology files rather than latest release
- init OntologyParser without schema_version arg, so it loads latest release. Unpin from schema 5.0.0, which is soon to be deprecated.
> fix: use latest ontology schema version for dry run

- cellxgene_schema_cli/cellxgene_schema/utils.py
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_utils.py
- feature_is_filtered validation check was previously loading X matrix into memory if bool column `var.feature_is_filtered` had any True entry. It would 1) subset the X matrix to only genes with featured_is_filtered is True and 2) validate (without chunking) that this filtered feature subsetted matrix had only zero values as declared by the feature_is_filtered column values.
- This would, as a result, load the X matrix into memory in order to 1) subset and then 2) count nonzero values and thus require higher resource provisioning in order to support use cases where the featured_is_filtered check was triggered.
- in feature_is_filtered validation check, leverage existing matrix nonzero counting function, _count_matrix_nonzero, which implements matrix chunking
- pass in new optional arg, …
> fix: use memory efficient matrix subsetting to validate feature_is_filtered

- .github/workflows/push_tests.yml
- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/requirements.txt
- cellxgene_schema_cli/setup.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- #1052 & #1053 
- see https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/drafts/5.2.1-experimental.md#development_stage_ontology_term_id
- use 5.2.1-experimental COG/ontology parser 
- add validation requirements for development_stage_ontology_term_id for Zebrafish
- unit tests
> feat: validate development_stage_ontology_term_id for Zebrafish

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/tests/test_schema_compliance.py
https://app.zenhub.com/workspaces/cs-platform-661fffc5c6339904f8f42cb2/issues/gh/chanzuckerberg/single-cell-curation/1046
- adds validation rules for organism_cell_type_ontology_term_id for fruit fly
adds unit tests
> feat: add validator changes for fruit fly cell type ontology term id

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/tests/test_schema_compliance.py
https://app.zenhub.com/workspaces/cs-platform-661fffc5c6339904f8f42cb2/issues/gh/chanzuckerberg/single-cell-curation/1067
- enforces that tissue type is 'tissue' for experimental species
added unit tests
> feat: enforce tissue_type = tissue for experimental species

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_validate.py
- #[1112](https://github.com/chanzuckerberg/single-cell-curation/issues/1112)
- seurat conversion is no longer supported and the validator need no longer check
- remove Seurat Validator and references to the Seurat Validator
- remove tests involving Seurat validator
- remove `seurat_is_convertible` status from the return signature for the `validate()` function
```
```
> chore: remove seurat references in validator

- cellxgene_schema_cli/requirements.txt
- scripts/schema_bump_dry_run_ontologies/requirements.txt
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/cellxgene-ontology-guide/241
- bumps COG version to 1.3.0, which i just released here: https://github.com/chanzuckerberg/cellxgene-ontology-guide/pull/243
n/a
> chore: bump cog version for schema 5.3.0

- schema/drafts/5.3.0.md
> Added genetic ancestry

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- cellxgene_schema_cli/tests/test_validate.py
- pyproject.toml
- #1105 
- compliance with 5.3 schema
- add NaN check for spatial embeddings - no NaNs allowed
- convenience change: pyproject.toml - pytest block adds cellxgene_schema_cli to python path
- added one test to test_validate
- modified existing test in test_compliance
```
```
- notice the change to pyproject.toml. It's useful for vscode dev (allows me to interactively debug tests) and it shouldn't interfere with other environments. I'm happy to take out if it has unintended consequences.
> chore: forbid any NaN in spatial embeddings #

- cellxgene_schema_cli/cellxgene_schema/utils.py
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- #1104 
- update `_validate_spatial_tissue_position` to support descendants of Visium
- refactor `_is_visium_including_descendants` to work around non-idempotent dependence on ONTOLOGY_PARSER [COG#246](https://github.com/chanzuckerberg/cellxgene-ontology-guide/issues/246)
- 
- `test_schema_compliance.test_column_presence_in_tissue` tests descendants and non descendants
```
```
- the implementation for checking descendants relies on a new utility method. This was just a way to have a single method implementation that can be used as an `apply()` function and be cached to avoid unnecessary graph traversals in ontology
-
> feat: update validation for obs['in_tissue'] to include descendants of Visiium

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/requirements.txt
- cellxgene_schema_cli/setup.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- #1128 (work for gencode / feature_reference done in separate PR)
- see corresponding c. elegans schema reqs in https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/drafts/5.2.1-experimental.md
- add c. elegans validation rules for:
- development stage ontology term ID
- sex ontology term ID
- organism_cell_type ontology term ID
- organism_tissue_type ontology term ID
- tissue_type
- COG ontology bump to use experimental COG release with c. elegans ontologies (1.3.2a0)
- bump CLI version to 5.2.1a2
- unit tests (no real c. elegans examples yet to test against)
> feat: add support for validating c. elegans

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- cellxgene_schema_cli/tests/test_validate.py
- #1099 
- apply spatial X requirements when assay is any descendant of visium
- different X row length depending on Visium 11mm vs any other Visium assay
- updated error messages to include Visium 11mm where relevant
- custom validator dynamic  properties (i.e. `@property`) for visium assay dependent values
- added paramterized tests for descendant visium assay and visium 11 assay
- There was a pretty hefty rebase required for this.
> feat: cellxgene-schema must update validation for X (Matrix Layers) for descendants of Visium

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- #1134 
- in cases where a unary operation is applied to "category" dtype column, be sure to cast the result as boolean
- a single test was added specifically for the 'assay_ontology_term_id' obs field checking that it works when encoded as a normal string or as a category.
- This should not introduce any new ambiguity, however, it does not remove existing ambiguity elsewhere in the codebase whereby some implicit assumptions about column encoding may be violated.
> fix: handle both string and category encoded "assay_ontology_term_id"

- schema/drafts/5.3.0.md
> updated sex_ontology_term_id

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_validate.py
makes the change to remove `is_seurat_convertible` more backwards compatible friendly by continuing to return `False`. we can remove this return value entirely with a future release, though i think it should technically be part of a major update if we do
- returns `False` as the final tuple value always
updated unit tests
> chore: add back return value from is_seurat_convertible

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_validate.py
- #1100 
- #1101 
- 5.3 schema compliance
- validator returns appropriate tissue position max values for visium and visium 11, respectively
- unit-tests cover min and max checks for visium and visium 11 assays
> feat: differential tissue position row/col max sizes for visium and visium 11

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- #1102 
- support for visium descendants in obs['assay_ontology_term_id'] 
- update `validator.reset()` function to include optional parameters to set key constants e.g. spatial hi res image size, tissue position matrix size.
- squash bug related to `categorial` vs `string` dtypes 
- no notes.
- updating the `reset()` function enables test fixtures to use smaller images and matrices, where necessary, without flagging additional errors.
> feat: support for visium descendants in obs['assay_ontology_term_id']

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- follow up based on QA feedback [from lattice](https://czi-sci.slack.com/archives/C07AV4NU9D2/p1732737017085079) to update logging to be based on donor id, instead of row indices
- updates the error log to be based on donor id instead of row indices
- i also moved the `_validate_genetic_ancestry` check into `_deep_check` because i realized that embedding it into the component level validation was causing it to be run multiple times, resulting in multiple errors
since this was mostly just a copy change, i updated `test_genetic_ancestry_same_donor_id` to print out the errors and to intentionally fail the test. here is the error message which shows the copy has been updated to show donor ids:
```
print(validator.errors)
>       assert len(validator.errors) == 0
E       assert 1 == 0
E …
```
> chore: update logging to log by donor id instead

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- Anecdotally, during testing for other tickets, suspension_type was taking unreasonably long for validate (>1 hr for dataset with 4M obs rows x 31 columns). 
- This is likely due to executing 1 query per rule in the schema definition rather than batching together queries that evaluate to the same suspension_type value. 
- The code for defining + evaluating dependency rules is quite complex and can be simplified given our use cases
- The trade-off for this complexity is slightly more specific error messages; I believe we can achieve similarly helpful error messages with slightly less specificity traded off for more performant, simpler code.
- refactor `schema_definition.yaml` to always use the (formerly known as) "complex_rule" format of defining your pandas queries in YAML rather than …
> feat: refactor suspension type validation logic to be simpler and more performant

- cellxgene_schema_cli/cellxgene_schema/cli.py
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/requirements.txt
This is faster an reduces the over head of maintaining the dask configuration. 
Using processes instead of threads was also tried, but processes used a lot more memory and disk, and didn't provide a significant speed boost.
- removed ``` num_workers, threads_per_worker, distributed.worker.memory.limit``` from `dask.config`. Using the default values improves speed and maintains constant memory.  ```threads_per_worker, distributed.worker.memory.limit``` are removed because they only work when using a distributed dask client.
- add `dask[array]`, this is to make sure we install a compatible numpy version.
- remove `n_workers` from the validate cli command. It is no longer used.
1. `pip install "dask[diagnostics]"
2.  Modify `cellxgene_schema.validate` to accept `scheduler` as a parameter.
3. …
> feat: use dask threads schedule with default values.

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- cellxgene_schema_cli/tests/test_validate.py
- the previous error logging was printing out all of the possible categorical values for `donor_id`, which would print out all possible donor id values. not just the donor id values for the invalid rows.
- `self.adata.obs.loc[invalid_rows, "donor_id"]` will only fetch the donor_id fields when `invalid_rows` for that index is true. so this will only print out the donor ids that are actually invalid
- i also added in a typo fix for this [line](https://github.com/chanzuckerberg/single-cell-curation/blob/60673117145bb27edd83cde3fa7fb62052e3a5b7/cellxgene_schema_cli/cellxgene_schema/validate.py#L1121) which should say `adata.obsm['spatial']` instead of `adata.obs['spatial]`
i tested this by just printing out the error log in `test_genetic_ancestry_same_donor_id`. previously, this error message …
> fix: donor id error logging + obsm typo

- cellxgene_schema_cli/cellxgene_schema/cli.py
- cellxgene_schema_cli/cellxgene_schema/gencode.py
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/cellxgene_schema/write_labels.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- cellxgene_schema_cli/tests/test_validate.py
This is part of the multiome work, where multiple validations steps will happen in parallel. If all steps pass then we will add labels. To accomplish this the Validator needed to be decoupled from the AnnDataLabelAppender. This allows the AnnDataLabelAppender to run independently of validation.
- Cache gene_checker in gencode.
- Replace the `Validator` parameter in `AnnDataLabelAppender` with `AnnData`
- Replace uses of `Validator` in `AnnDataLabelAppender`
- add cli to add labels to h5ad
- fix relative imports
- remove AnnDataLabelAppender.was_writing_successful
- Updates tests
> fix: remove dependency on Validator in AnnDataLabelAppender

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- cellxgene_schema_cli/tests/test_validate.py
- requirements-dev.txt
- #1189 
- 
- exclude self when checking if assay is a descendant of EFO:0010961
- remove use of EFO:0010961 from tests where it is expected to yield a successful validation
- add explicit test for EFO:0010961 and append a custom error message for this error.
- Most of the test updates were to replace EFO:0010961 with a lower, valid term e.g. EFO:0022857 (v1) or EFO:0022858 (v2) or EFO:0022859 (6.5mm)
```
```
- Lattice confirmed that the existing error messages related to valid spatial assays is sufficient. 
- it would be nice to extend the schema validator to include visium checks - perhaps this is a maintenance task.
> feat: exclude generic visium (EFO:0010961) from allowed assay_ontology_term

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_map_species.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- cellxgene_schema_cli/tests/test_validate.py
- #1225 
- purely changes to testing functions
- no additional  tests
There were two issues here
The validator hardcodes the expected matrix size. Our test fixtures, however, use much smaller test matrices. To nudge the validator to accept this simply reset with the expected size e.g. `validator.reset(None, 2)`
The source of the problem is that the test updated the organism-specific column e.g. `obs["organism_cell_type_ontology_term_id"]` but the validator is only checking the organism-agnostic column e.g. `obs["cell_type_ontology_term_id"]`.  Quick fix is to update the tests to change the organism-agnostic column.
I think this should be fine given that we are deprecating the organism-specific column in the official 5.3. 
> [!IMPORTANT] remove `organism_<column>`
> all of the …
> feat: resolve visium+multispecies testing conflicts

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
there's a few issues here that this PR addresses:
- we need to make sure that zebrafish / fruit fly / roundworm still accepts valid CL terms for `tissue_ontology_term_id`, but _only_ when `tissue_type == cell culture`
- also, UBERON terms should be supported for `tissue_ontology_term_id` even if species is zebrafish / fruit fly / roundworm
- and CL terms should be supported for `cell_type_ontology_term_id`  even if species is zebrafish / fruit fly / roundworm
this PR: https://github.com/chanzuckerberg/single-cell-curation/pull/1231/files introduced some issues with these 3 cases weren't being properly handled with moving the logic to the schema def. so i've moved the organism-specific logic back into the validate script directly.
we will revisit an approach to writing out the validation …
> fix: tissue_ontology_term_id and cell_type_ontology_term_id fields for 3 new species

- cellxgene_schema_cli/tests/test_map_species.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
- some tests were skipped when merging experimental multi-species validator
- unskipped map-species tests. We still want this functionality to work, even if we aren't exposing it or using it as part of any CI operation
- removed test related to `cell_type_ontology_term` = 'na'. It's redundant to the check for 'unknown'.
- some tests removed
- no skipped tests
Lattice team may experience some interesting error messages if they use any non-ontology value for `obs["cell_type_ontology_term_id"]` when it should be 'unknown'. But this is a reporting issue, and not related to test coverage.
> chore: resolve/remove skipped tests

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
feedback from brian mott: https://czi-sci.slack.com/archives/C07AV4NU9D2/p1738627367824459?thread_ts=1738345846.792719&cid=C07AV4NU9D2
When tissue_type == cell culture, then the rules for cell_type_ontology_term_id should apply for tissue_ontology_term_id. However, only CL terms are valid in this case, instead of both CL and the respective organism cell ontology (FBbt, ZFA, or WBbt)
i also picked up one of the minor nits which was to remove the `\n` from error messages
- updates the validator to ensure that this case is now caught properly. this does make the schema definition even more janky.
- @ejmolinelli i do recall you mentioning that we can easily extend the validator to name rules and apply rules in certain areas. i wasn't sure if you made much (or any) progess actually writing …
> fix: cell culture edge case for zebrafish, fly, roundworm

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/requirements.txt
- cellxgene_schema_cli/tests/test_schema_compliance.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/1243
- updates schema definition to add support for mus musculus descendants
- upon further inspection it appears as if the print output for `ONTOLOGY_PARSER.get_term_descendants("NCBITaxon:10090", include_self=True)` is simply `term_descendants ['NCBITaxon:10090']`
added unit tests to ensure mouse descendant terms are accepted
> feat: add support for mus musculus descendant organisms

- cellxgene_schema_cli/cellxgene_schema/gencode.py
- cellxgene_schema_cli/tests/fixtures/examples_ontology_test.py
- we received feedback from lattice [here](https://czi-sci.slack.com/archives/C07AV4NU9D2/p1738878739392169?thread_ts=1738345846.792719&cid=C07AV4NU9D2) that some fruit fly genes start with `RR`
- updated the gencode mapper to account for this
- added fruit fly genes to `valid_genes` in `test_gencode`
> fix: fruit fly RR genes

- cellxgene_schema_cli/cellxgene_schema/gencode.py
- cellxgene_schema_cli/tests/test_gencode.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
it seems like the issue with `RR` prefixed genes with fruit fly was a bit of a patchwork solution to a slightly bigger problem, which is that inferring organism species based on gene id prefix is not entirely correct. see [this](https://czi-sci.slack.com/archives/C07AV4NU9D2/p1738957962258369?thread_ts=1738896679.479739&cid=C07AV4NU9D2) issue with a gorilla gene prefixed with `ENSGGOG` gets incorrectly mapped to homo sapiens
- updates implementation of `gencode.get_organism_from_feature_id` to go through each individual gene checker, rather than rely on gene prefix
- updates a test in `test_gencode` to assert that we're mapping the organism from feature id correctly
> fix: determine species from gene file, not from gene prefix

- cellxgene_schema_cli/cellxgene_schema/atac_seq.py
- cellxgene_schema_cli/cellxgene_schema/cli.py
- cellxgene_schema_cli/cellxgene_schema/ontology_parser.py
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/cellxgene_schema/write_labels.py
- cellxgene_schema_cli/tests/test_atac_seq.py
- [Mulitome: unsupported organism_ontology_term_id returns an ambiguous KeyError rather than a validation error message](https://github.com/chanzuckerberg/single-cell-curation/issues/1280)
- [Multiome: negative values in the fifth_column must fail validation](https://github.com/chanzuckerberg/single-cell-curation/issues/1282)
- [Multiome: using incorrect chromosome table returns an ambiguous pandas exception rather than a validation error message](https://github.com/chanzuckerberg/single-cell-curation/issues/1283)
- [Multiome: validation error messages are "lost in all the output"](https://github.com/chanzuckerberg/single-cell-curation/issues/1277)
- [Multiome: anndata validation should occur before fragment file validation](https://github.com/chanzuckerberg/single-cell-curation/issues/127 …
> fix: atac fragment processing suggestion

- notebooks/curation_api/python/src/dataset.py
- notebooks/curation_api/python/upload_local_datafile_to_dataset.ipynb
- Now that the manifest endpoint is used to upload datasets from the submission bucket, the notebook `upload_local_datafile_to_dataset` must be updated to use the new work flow. Now local files are uploaded to s3, and the resulting `s3_uri` will populate the manifest. The manifest submission endpoint will be called with the newly uploaded files and ingestion will start. 
- update the upload_local_datafile to return an s3_uri 
- Use the local file name i the s3 object key.
- update `upload_local_datafile_to_dataset` to use the manifest endpoint and build the manifest.
-
> feat(multiome): Update the upload_local_datafile_to_dataset.ipynb to use a manifest.

- .github/workflows/gencode-bump-dry-run.yml
- cellxgene_schema_cli/cellxgene_schema/gencode_files/gene_info.yml
- cellxgene_schema_cli/requirements.txt
- cellxgene_schema_cli/scripts/readme.md
- scripts/schema_bump_dry_run_genes/gene_bump_dry_run.py
- scripts/schema_bump_dry_run_genes/requirements.txt
- scripts/schema_bump_dry_run_ontologies/requirements.txt
Update (a) gene info files and (b) COG version to comply with cxg schema 5.3.0.
- update COG version in requirements
- update to gene info.
```
```
> feat: schema 5.3.0 gene bumps

- cellxgene_schema_cli/cellxgene_schema/atac_seq.py
This reverts commit 3250f5a7a90491b30cd395491d3abd6c4e744b4a.
It turns out that dask needs to read the entirety of a gzipped csv into memory
> Revert "Remove decompressed intermediate (#1308)"

- cellxgene_schema_cli/cellxgene_schema/atac_seq.py
- cellxgene_schema_cli/requirements.txt
- cellxgene_schema_cli/tests/test_atac_seq.py
Speed up conversion to parquet by skipping intermediate decompressed tsp
- This uses the iterative CSV reader and iterative parquet writer from pyarrow.
```
```
[Here is a small notebook](https://gist.github.com/ivirshup/248a2931d6e78cf72dedd9520af0e8de) where I took some performance metrics. I'm seeing about a 3x speed up on conversion and 1/5th memory …
> New approach using pyarrow for IO

- cellxgene_schema_cli/cellxgene_schema/atac_seq.py
- cellxgene_schema_cli/requirements.txt
- cellxgene_schema_cli/tests/test_atac_seq.py
We have been running out of memory while validating large atac seq fragment files. This PR address this by doing the validation with duckdb instead of dask-dataframe.
With these changes I was able to validate our largest dataset in ~5 minutes on a `m5ad.8xlarge` (125gb memory, 32 CPU) whereas I ran out of memory with the previous implementation.
- 
```
```
> Optimize validation with duckdb

- cellxgene_schema_cli/tests/test_atac_seq.py
- test that the correct number of rows per chromosome are in the new fragment file
- maintain the integrity of the generated fragment by testing for the correct number of rows for each chromosome.
> fix: verify sorted fragment contents

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/cellxgene_schema/utils.py
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
These fixes address issues that emerged as part of the schema migration. 
- ERROR: 'CL:0000000' in 'cell_type_ontology_term_id' is not an allowed term id.
- sparse array length is ambiguous; use getnnz() or shape[0]  - this error occurs as a result of a sparse matrix in `anndata.uns`
- allow specific terms in schema_definition e.g. CL:0000000
- support reading `csc` sparse matrices in `uns` element
- support for validating dask arrays in `uns` element
- added tests for validating empty/non-empty `anndata.uns` sparse matrices, regardless of sparse format.
> feat: schema 5.3 migration

- .github/workflows/publish-to-pypi.yml
- fix a deprecation warning from pypi by upgrading setuptools
- upgrade setuptools before building python distribution of cellxgene-schema.
- verified that building works with the latest setuptools and pypi doesn't complain about it's naming
> fix: upgrade setuptools before building

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/cellxgene_schema/validation_internals/check_duplicates.py
- cellxgene_schema_cli/tests/fixtures/examples_validate.py
- cellxgene_schema_cli/tests/test_check_duplicates.py
- cellxgene_schema_cli/tests/test_map_species.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/1317
- after spending ~30 mins writing my own hash algorithm that all seemed to break my local machine, i pivoted and based this PR off of this code snippet lattice provided for evaluating duplicate obs rows: https://github.com/Lattice-Data/lattice-tools/blob/a9f7129f43e5cc1e910e513d0efd3ca1412e59cb/cellxgene_resources/cellxgene_mods.py#L450-L513
- i made some changes to this, notably:
- switched from `sha1` to `sha224`, which is faster
- updated it to support reading in a dask array instead of a csr matrix
- some basic code clean up like changing variable names, using list comprehension, etc
note that i also put all of this logic in a separate file, `check_duplicates.py` …
> feat: validate that no two rows in obs are identical by row counts

- cellxgene_schema_cli/MANIFEST.in
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/cellxgene_schema/validation_internals/check_duplicates.py
- cellxgene_schema_cli/setup.py
discovered that despite the tests passing, we can't actually run the CLI because of how we're doing the package setup
- primary change is to update the package setup to just pull in everything from `cellxgene_schema`, rather than needing to further specify all the subdirectories in there. this seems fine to me as i think we can reasonably assume anything within that subdirectory we'd want to include
- ran `pip install ~/src/single-cell-curation/cellxgene_schema_cli` and verified i could then run `cellxgene-schema validate input.h5ad`
> fix: package setup with validation_internals

- cellxgene_schema_cli/cellxgene_schema/atac_seq.py
- this PR aims to resolve https://czi.atlassian.net/jira/software/c/projects/VC/boards/1534?selectedIssue=VC-2554
- delete intermediate files when compressing to bgzip.
```
```
> fix: clean up intermediate sort files for ATAC

- cellxgene_schema_cli/cellxgene_schema/validation_internals/check_duplicates.py
- cellxgene_schema_cli/tests/test_check_duplicates.py
it looks like we actually only want to check the raw matrix for the duplicate rows. so if `raw.X` is provided, then that is the raw matrix. otherwise, we assume `X` is the raw matrix.
context: https://czi-sci.slack.com/archives/C08MF1AJ6F5/p1746570075756179?thread_ts=1746028640.679369&cid=C08MF1AJ6F5
- updated the logic / comments accordingly
i added more test coverage to make sure we only raise the error for the raw matrix
> fix: only check duplicate rows of raw matrix, not normalized matrix

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
the validation for `feature_is_filtered` fails with an `IndexError` if you pass in invalid anndata: https://czi-sci.slack.com/archives/C08MF1AJ6F5/p1747163016677619?thread_ts=1746730671.752919&cid=C08MF1AJ6F5
- updated the validator to specifically catch the `IndexError` in this case
- i wrapped the full validation in a try/except loop that way if we run into a similar issue in the future, we don't get an uncaught exception. the validation script will just print out the relevant error
- added test coverage that we generate the error "ERROR: Could not complete full validation of feature_is_filtered because of size differences between var and raw.var."
> fix: catch indexerror

- cellxgene_schema_cli/cellxgene_schema/migrate.py
- cellxgene_schema_cli/cellxgene_schema/utils.py
- cellxgene_schema_cli/tests/test_migrate.py
- cellxgene_schema_cli/tests/test_utils.py
- scripts/migration_assistant/migration_template.jinja
- scripts/migration_assistant/tests/test_convert_template.py
- related to the work on moving organism from obs to uns: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/1311
- updates the migration script template to migrate organism terms through `uns`, using a new helper function `replace_ontology_term_uns`. for the schema 6.0 migration, i wrote `move_ontology_term_from_obs_to_uns` to migrate terms from `obs` to `uns`, in addition to performing the mapping for deprecated terms
- updated tests in `test_migrate` and `test_convert_template`
> feat: update migration script for moving organism from obs to uns

- cellxgene_schema_cli/cellxgene_schema/atac_seq.py
- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/conftest.py
- cellxgene_schema_cli/tests/test_atac_seq.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
feedback from lattice here: https://czi-sci.slack.com/archives/C08MF1AJ6F5/p1747951638945869?thread_ts=1747337258.902249&cid=C08MF1AJ6F5
i'll put up a separate PR after i get:
- clarification for how we want to treat covid / spike-ins
- clarification on if we want to remove the column dependency errors
- updates `atac_seq.py` to read `organism_ontology_term_id` from `uns` instead of `obs`
- declares `organism_ontology_term_id` to be a deprecated column of `obs`, so that it's invalid if that column is provided
- updates `organism_ontology_term_id` to be explicitly required in `uns`, rather than relying on the organism dependency error messages
- i updated the relevant tests in `test_atac_seq`, and i also added some additional test coverage for checking to see if organism is present or not
> fix: organism validation for atac_seq 6.0

- cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
https://czi-sci.slack.com/archives/C08MF1AJ6F5/p1748623273521219?thread_ts=1747337258.902249&cid=C08MF1AJ6F5
- i had only deprecated `organism_ontology_term_id` in obs, we should also deprecate `organism`
updated the existing test to check for both deprecated columns
> fix: deprecate organism column in addition to organism_ontology_term_id

- cellxgene_schema_cli/cellxgene_schema/validate.py
https://czi-sci.slack.com/archives/C08MF1AJ6F5/p1748633110413779?thread_ts=1747337258.902249&cid=C08MF1AJ6F5
- this error message should just print out the unique organisms detected for invalid feature ids, not.. one item for each invalid feature id lol
n/a
> fix: unique organisms from feature ids

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
output from this slack thread: https://czi-sci.slack.com/archives/C08MF1AJ6F5/p1748624494894579
- adds validation checking to forbid labeled columns specified in `uns["keys"]` and fail validation as a result
- added a unit test to cover this
> fix: forbid organism from being provided in uns

- cellxgene_schema_cli/cellxgene_schema/migrate.py
- cellxgene_schema_cli/cellxgene_schema/utils.py
- cellxgene_schema_cli/tests/test_migrate.py
- cellxgene_schema_cli/tests/test_schema.py
- cellxgene_schema_cli/tests/test_utils.py
a few changes here, based on feedback from lattice in [this thread](https://czi-sci.slack.com/archives/C08MF1AJ6F5/p1749151615477039?thread_ts=1749139807.104259&cid=C08MF1AJ6F5)
- added a new util method `replace_delimiter` to migrate the delimiter of `self_reported_ethnicity_ontology_term_id`
- i updated the logic in `move_column_from_obs_to_uns` to log a warning instead of raising a keyerror if the column isn't found. mostly just because it makes writing the migration unit test easier, but i also think we shouldn't fail the migration if the column isn't found in case we need to re-run migration for something that is partially migrated or something like that.
- added test coverage for `replace_delimiter`
- fixed a few random tests that were failing that were introduced when i merged my …
> feat: update migrate script

- cellxgene_schema_cli/cellxgene_schema/map_species.py
- cellxgene_schema_cli/cellxgene_schema/ontology_parser.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
as titled. i realized when i bumped COG to 1.7.2, i forgot to bump to 6.0.0 in the ontology parser 🤦‍♀️ 
- looks like `CL:0007021` was deprecated, so i replaced it with a random valid CL term in the tests that use that.
> chore: bump ontology parser version

- scripts/schema_bump_dry_run_ontologies/ontology_bump_dry_run.py
- scripts/schema_bump_dry_run_ontologies/tests/fixtures/group_datasets_by_collection_expected
- scripts/schema_bump_dry_run_ontologies/tests/fixtures/no_deprecated_terms_with_open_revisions
- scripts/schema_bump_dry_run_ontologies/tests/fixtures/with_comments_and_considers_expected
- scripts/schema_bump_dry_run_ontologies/tests/fixtures/with_replaced_by_diff_ontology_expected
- scripts/schema_bump_dry_run_ontologies/tests/fixtures/with_replaced_by_expected
- scripts/schema_bump_dry_run_ontologies/tests/fixtures/with_term_tracker_expected
- it seems like we still want to generate the `revision_map` to pass in to `write_to_curator_report`, we just don't want to include language that states these collections won't be auto-migrated
- slack context here: https://czi-sci.slack.com/archives/C08MF1AJ6F5/p1749491523566209?thread_ts=1749139807.104259&cid=C08MF1AJ6F5
- removes the portion of the script which writes this language
n/a
> chore: remove printing out collections with an open revision in them

- cellxgene_schema_cli/cellxgene_schema/cli.py
- cellxgene_schema_cli/cellxgene_schema/matrix_utils.py
- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/cellxgene_schema/validation_internals/check_duplicates.py
- cellxgene_schema_cli/requirements.txt
- OOMs on large datasets during latest migration dev run, identified this as a point of memory leakage (still OOMs on datasets with 2M+ cells even after increasing to 64GB RAM machines)
- original implementation introduced [here](https://github.com/chanzuckerberg/single-cell-curation/pull/1395/files)
- use dask's built-in 'sum' function, which can sum over dask array sparse matrix columns in a memory-optimized way (manages intermediate sums efficiently using tree-reduction)
- set optional 'split_every' arg to 8, to limit number of intermediate artifacts held in RAM
- requires converting blocks to COO matrices to be compatible with built-in sum function
- custom implementation was holding many intermediate artifacts (dense array blocks) concurrently in memory, causing OOMs.
-  Alternative …
> fix: memory optimization in feature_is_filtered validation

- cellxgene_schema_cli/cellxgene_schema/atac_seq.py
- cellxgene_schema_cli/tests/test_atac_seq.py
- add a step to verify no duplicate rows were created during the conversion process.
- add a step to count lines in the original and generated compressed files, and compare the results 
- added unit tests for the new functionality.
A patch release of 6.x will be needed with this change
> fix: atac seq duplicate check

- cellxgene_schema_cli/cellxgene_schema/validate.py
- cellxgene_schema_cli/tests/test_schema_compliance.py
https://czi-sci.slack.com/archives/C07AV4NU9D2/p1755897599662919?thread_ts=1755889725.833399&cid=C07AV4NU9D2
- replaces return with continue, so that we append errors for each invalid gene
updated an existing test we had to ensure we would return 2 errors for 2 invalid genes
> fix: invalid gene check

- cellxgene_schema_cli/cellxgene_schema/atac_seq.py
- cellxgene_schema_cli/cellxgene_schema/cli.py
- cellxgene_schema_cli/tests/test_atac_seq.py
- a continuation of https://github.com/chanzuckerberg/single-cell-curation/pull/1427
- add a cli command to deduplicate an ATAC fragment.
- sort by the 4th column
- limit the amount of memory per thread when sorting.
- add CLI command to deduplicate an atac fragement
- added test case for deduplicating atac fragments
add to [release 6.0.4](https://github.com/chanzuckerberg/single-cell-curation/pull/1429)
> fix: stricter control on sorting

- cellxgene_schema_cli/requirements.txt
fixing a bug when ingesting ATAC datasets
```
{ "levelname": "ERROR", "asctime": "2025-09-16T18:04:14.016Z", "name": "processing", "message": "validation failed", "lineno": 185, "pathname": "/backend/layers/processing/process_validate_atac.py", "exc_info": "Traceback (most recent call last):\n File \"/backend/layers/processing/process_validate_atac.py\", line 180, in process\n errors, fragment_index_file, fragment_file = self.schema_validator.validate_atac(\n File \"/backend/layers/thirdparty/schema_validator_provider.py\", line 102, in validate_atac\n atac_seq.process_fragment(fragment_file, anndata_file, True, output_file=output_file),\n File \"/opt/venv/lib/python3.10/site-packages/cellxgene_schema/atac_seq.py\", line 226, in process_fragment\n errors = …
```
> fix: pin duckdb version in requirements.txt

- .bumpversion.cfg
- cellxgene_schema_cli/cellxgene_schema/__init__.py
- cellxgene_schema_cli/cellxgene_schema/schema.py
- cellxgene_schema_cli/setup.py
- cellxgene_schema_cli/tests/test_schema.py
- Recent case where package version was updated to address a bug, but schema version was not intended to be bumped. 
- bumpversion.cfg, if run locally, updates the schema version without committing the change to git, leading to confusion when the schema_version being minted does not match files committed in main
- schema_version is now a separate var from package version, must be updated manually rather than in one-go with bumpversion (this is reasonable given that bumpversion is designed for package versioning)
- update package version to 6.2.2 to match the patch release this will go out with, update schema version to 6.0.0 as expected
> fix: decouple schema version from package version

- cellxgene_schema_cli/cellxgene_schema/__init__.py
- cellxgene_schema_cli/cellxgene_schema/ontology_parser.py
- cellxgene_schema_cli/requirements.txt
- scripts/schema_bump_dry_run_ontologies/requirements.txt
This pull request updates the codebase and dependencies to support schema version 7.0.0 and the latest stable release of `cellxgene-ontology-guide`. The changes ensure consistency across the schema version, ontology parser usage, and package requirements.
Schema and ontology updates:
* Updated `__schema_version__` to `"7.0.0"` in `cellxgene_schema/__init__.py` to reflect the new schema version.
* Changed the `OntologyParser` initialization to use schema version `"v7.0.0"` instead of the alpha version in `ontology_parser.py`.
Dependency upgrades:
* Upgraded `cellxgene-ontology-guide` to version `1.9.0` in both `cellxgene_schema_cli/requirements.txt` and `scripts/schema_bump_dry_run_ontologies/requirements.txt` to use the latest stable release. …
> feat: update schema version to 7.0.0 and bump COG to 1.9.0
